### ISSUE TITLE
Reset rmapi

### ISSUE THREAD

**Issue by fabiosirna** [juruen/rmapi#10]
Hi,
how can I reset the rmapi in order to ask a new code? I think I have 2 accounts on remarkable so I can't see the right folders and I want to reset it. Thanks

**Comment by juruen** [comment]
@fabiosirna what operating system are you using?

rMAPI reads the configuration from `~/.rmapi`

**Comment by lobre** [comment]
@juruen, maybe we can think of a specific command like `rmapi reset` that would clear any credentials registered whatever the OS?

**Comment by malaninnova** [comment]
> @juruen, maybe we can think of a specific command like `rmapi reset` that would clear any credentials registered whatever the OS?

Was this enhancement completed? I have tried to run using rmapi version: 0.0.19 and rmapi reset does not work

**Comment by posita** [comment]
Perhaps the user config location and steps to remove it should be documented?
