### ISSUE TITLE
rmapi upload generates empty pdf

### ISSUE THREAD

**Issue by patrickpichler** [juruen/rmapi#107]
When uploading a pdf with rmapi 0.0.11 all uploaded pdfs are empty.

I'm running on voidlinux and use the package from the void package      
registry (which I maintain).                                            

It also happens when I'm using the compiled binary from the release
page.

**Comment by ddvk** [comment]
i ll look into it. can you provide a samplle file?

**Comment by patrickpichler** [comment]
I think I found the issue. It happens when I try uploading pdfs without
an extension. It used to work pre v0.0.11.

**Comment by ddvk** [comment]
closing this, now there is an error when the file extension is not supported (currently .epub, .pdf and .zip)
