### ISSUE TITLE
mirrowed thumbnails

### ISSUE THREAD

**Issue by patrickpichler** [juruen/rmapi#108]
Starting with rmapi v0.0.10 I noticed that the thumbnails are mirrowed.

I'm running voidlinux and use the rmapi package from the void           
repository (which I maintain).

**Comment by patrickpichler** [comment]
Version v0.0.11 seems to fix this issue.

**Comment by ddvk** [comment]
the thumbnail generation (from rmapi) was made optional (can be enabled with RMAPI_THUMBNAILS=1 env variable). the underlying pdf library has some issues apparently.
