### ISSUE TITLE
Putting epubs

### ISSUE THREAD

**Issue by yacc143** [juruen/rmapi#11]
Hi!

Seems like putting epub files does not work.

Downloading the "epub" back from rmapi, gets me a zip file that contains:
Archive:  test.epub.zip
  inflating: 40e23248-92b4-41ef-845c-73e2fa4fecbd.pdf  
  inflating: 40e23248-92b4-41ef-845c-73e2fa4fecbd.pagedata  
  inflating: 40e23248-92b4-41ef-845c-73e2fa4fecbd.content  

And the "pdf" file inside the zip is actually the epub file:
file 40e23248-92b4-41ef-845c-73e2fa4fecbd.pdf 
40e23248-92b4-41ef-845c-73e2fa4fecbd.pdf: EPUB document

Any ideas?

TiA, Andreas

**Comment by juruen** [comment]
> Seems like putting epub files does not work.

Yeah, I've never uploaded an epub to my rM. Give me some time to test it myself.

**Comment by juruen** [comment]
@yacc143 I had some time this weekend to add support for `epub` files.  You can try the latest version of master.
