### ISSUE TITLE
Not opened document synchronized again after tablet reboot

### ISSUE THREAD

**Issue by ademasi** [juruen/rmapi#111]
Thanks for your incredible work.  I have been using rmapi since I got my remarkable, it is so useful.

I have been uploading of a lot of documents (pdfs mostly) using rmapi. 

I found a weird behaviour that I am not able to explain. I was able to reproduce it on the default xochitl, I normally use the patched version from @ddvk (also big thank you). This is present with 0.0.11 and the current master.

Once a document has been upload via rmapi, if it has not been open on the device, every time the tablet reboot and/or xochitl restart the document is downloaded again.  This does not happen for file uploaded via the smartphone application.

Looking at the logs on the tablet, I see this message:
` 
Failed to remove marker file to indicate entry is finished downloading (setDownloading(bool, int,bool) ../git/src/library/entry.cpp:674)
`
Did RM updated the way their cloud is functioning ?

**Comment by ddvk** [comment]
are you sure this hapens every time? i’ve seen it a couple of times, but didnt pay much attention.

**Comment by ademasi** [comment]
You are welcome.

Yes, if the document has been opened on the tablet, it does not get download again. 

I am running 2113, I have flashed the tablet 2 times with the uuu tool and did a factory reset to be sure it was an issue from the system.

**Comment by ddvk** [comment]
this should be fixed now, but if you could try with the master and confirm would be nice. (the warning in xochtil still appears but not sure if this is connected).

**Comment by ademasi** [comment]
I confirm, it is fixed. I just tried master.

Thank you.
