### ISSUE TITLE
resync needed for some pdf

### ISSUE THREAD

**Issue by verbavolant** [juruen/rmapi#113]
Hi, sometimes when i'm using rmapi i can't find some pdf i've send a few days before: i need to join wifi and resync. It seems remarkable loses the preview.
Thanks for you work!

**Comment by ddvk** [comment]
does it happen with the latest master?

**Comment by verbavolant** [comment]
i've build rmapi two weeks ago, i'm working now with the lastest one. I'll tell you if something changes!

**Comment by ddvk** [comment]
i think we can close this one?
