### ISSUE TITLE
pdf's generated don't display correctly under windows/acrobat

### ISSUE THREAD

**Issue by torwag** [juruen/rmapi#114]
Tested with the attached PDF,
using rmapi 'geta', to export the annotated PDF back to the host, one receives a PDF which is ok on most (if not all) linux based pdf-viewers. However, under Windows and the Adobe Acrobat Reader, the annotations are not visible. This can create all kind of confusions sending those documents around. This bug is nasty, as esp. those who use rmapi are those who do not use Adobe Acrobat (linux users)  and hence do not see this problem.
It is also reproducible under linux, by using imagemagicks "convert" trying to convert the annotated PDF into an image. 

The test set contains:
test.pdf - original pdf (without annotation)
test.zip - export via rmapi after annotation
test-annotated.pdf - export via rmapi after annotation
test.png - conversion via imagemagick convert of test-annotated.pdf (this reproduces the error that the annotation is gone)

Test environment: 
Arch Linux
rmapi latest release via AUR package 0.0.11
ImageMagick 7.0.10-19
rM on 2.1.1.3

[test_all.zip](https://github.com/juruen/rmapi/files/4794798/test_all.zip)

UPDATE:
Workaround for the time being:
soffice --convert-to pdf filename.pdf
Creates a new PDF which seems to work (tested by imagemagick, still not confirmed for Adobe Acrobat)

**Comment by torwag** [comment]
Hi, I still need to test this, but I do not see why it should not work if @ddvk  was able to fix this for windows/adobe. This bug-fix, together with some other might be worse to get a new small release bump. As I wrote the bug is a bit a pain, as the users might not see the problem until they send a document to someone who uses windows/adobe. The missing annotation could potentially create all kind of trouble for them.

**Comment by juruen** [comment]
> This bug-fix, together with some other might be worse to get a new small release bump.

Done. Thank you for reporting this, and thank so much to @ddvk for the quick fix!

**Comment by juruen** [comment]
I believe we can close this one.

**Comment by torwag** [comment]
Yes, I can confirm it works and I can also confirm that the small release bump is on its way in different distributions. The AUR of Arch Linux was already updated.
