### ISSUE TITLE
PDF with annotation that includes pages without annotations doesn't retain Table of Contents/Outline

### ISSUE THREAD

**Issue by fmagin** [juruen/rmapi#120]
Currently when using `geta` to download the PDF file the resulting document consists only of the pages that actually have annotations. I am assuming this is a deliberate choice, and it seems sensible to me for most cases. But I think there are some scenarios where it is useful to generate a full PDF that closely mirrors the original, just with added annotations. For example to have a full functioning PDF of a textbook with table of contents, links, etc that still includes the added annotations/markings.

I am not quite sure which aspects of this are how much work. Simply adding the non annotated pages to the resulting PDF seems easy. Preserving the ToC, Links etc and adding annotations (especially the highlighter ones that get converted to machine extractable PDF annotations which is awesome!) might be harder. But possibly this is actually fairly easy, given that PDFs support incremental changes and edits. Adding the PDF highlighter tool annotations to a document without changing anything else seems possible, then adding the pen tools as another layer should also be doable.
Depending on the complexity I can work on this too, but I am not yet familiar with the specific PDF Library used, so any pointers are appreciated.

**Comment by ddvk** [comment]
there is a option -a for this

**Comment by fmagin** [comment]
thanks!

Then this is basically a usability issue, I didn't expect any commands to allow flags.

`geta` just prints `Error: missing source file`
`help geta` prints the same output as `help`
`geta help` prints the help for `geta` which I find surprising, but this doesn't mention flags either.
`geta -h` prints the flags for `geta`, but this already requires me to expect it to support flags. For other commands I just tried I just get errors that `-h` isn't a valid file.


Not sure if and how the CLI package supports it, but I'd expect there to be some way to easily include the supported flags in some help output.

**Comment by fmagin** [comment]
I guess this is still not fully functional after all: The resulted PDF will not include the Table of Contents of the original. Especially for the case of a textbook this can be quite important. Reopening this.

**Comment by ddvk** [comment]
this is a tough one.  unipdf has a reader and writer, so far i don't see a way to just modify an existing file.
