### ISSUE TITLE
auth.go:82: failed to create a new device token

### ISSUE THREAD

**Issue by verbavolant** [juruen/rmapi#124]
Hello! i've got this problem with a new device:

Enter one-time code (go to https://my.remarkable.com/connect/desktop): XXXXXXXXX
Trace: 2020/09/04 09:46:42 transport.go:172: request: POST /token/json/2/device/new HTTP/1.1
Host: my.remarkable.com
Authorization: Bearer
User-Agent: rmapi

{"code":"XXXXXXX","deviceDesc":"desktop-linux","deviceID":"XXXXXXXXXXXXXXXXXXXXX"}
Trace: 2020/09/04 09:46:42 transport.go:184: HTTP/2.0 403 Forbidden
Content-Length: 1519
Content-Type: text/html; charset=UTF-8
Date: Fri, 04 Sep 2020 07:46:42 GMT

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Access is forbidden.  <ins>That’s all we know.</ins>
Trace: 2020/09/04 09:46:42 transport.go:187: request failed with status 403
ERROR: 2020/09/04 09:46:42 auth.go:82: failed to create a new device token

**Comment by juruen** [comment]
@verbavolant could you try please to repeat the process but this time you generate the code by clicking `Reconnect your reMarkable`?

**Comment by verbavolant** [comment]
Nothing, same error!

**Comment by ddvk** [comment]
you sure you are not behind a proxy? (just tested it and it works with 'reconnect your remarkable'

**Comment by juruen** [comment]
@verbavolant I just tried to reconnect my old device generating an new code and I didn't have any issues.

Does it work fine if you try to use a new code in your mobile or desktop app?

**Comment by verbavolant** [comment]
Sure, direct.
From mobile, works.
I think i've been blacklisted (cron rmapi) because i push every 10 minutes..

**Comment by verbavolant** [comment]
confirmed: server changed, another ip, it works. 
I'll wrote to remarkable, but i think it's a ban, too many checks.
Thanks.

**Comment by juruen** [comment]
> confirmed: server changed, another ip, it works.
> I'll wrote to remarkable, but i think it's a ban, too many checks.
> Thanks.

That solves the mystery then!

Out of curiosity, may I ask why do you push so often? 😄

**Comment by verbavolant** [comment]
A bug in my script [1]: every minute the script looks in a nextcloud share: if a pdf is written it gets the file and sends to remarkable...
The bug was: pdf or not, rmapi talks to remarkable server, every minute.. :-)

[1] https://github.com/verbavolant/reMarkable-autosync

**Comment by verbavolant** [comment]
Hmm would like to improve your rmapi and add a polling option (i use rclone) and sync a remote directory to remarkable?

**Comment by ddvk** [comment]
polling is not ideal, but you can open a websocket and listen for
notifications

**Comment by verbavolant** [comment]
Could i make a push system from dropbox to rmapi?

**Comment by ddvk** [comment]
> Could i make a push system from dropbox to rmapi?

for that i suppose you have to listen for dropbox events and just push/delete files with rmapi

**Comment by ddvk** [comment]
closing this as resolved
