### ISSUE TITLE
Cannot reauthenticate after revoking token via my.remarkable

### ISSUE THREAD

**Issue by wietsedv** [juruen/rmapi#129]
I have disconnected the rmapi app via my.remarkable.com/list/desktop. When I try to run rmapi afterwards, it breaks with the following error:

`ERROR: 2020/11/18 09:50:38 auth.go:94: failed to create a new user token`

What happens is that rmapi tries to create a new user token based on the invalidated device token. I think that rmapi should recognize that the device token does not work anymore.

I solved my problem by deleting `~/Library/Application\ Support/rmapi/rmapi.conf` (macos).

**Comment by ddvk** [comment]
should be fixed now
