### ISSUE TITLE
cd into a directory with " " space in its name

### ISSUE THREAD

**Issue by elexx** [juruen/rmapi#131]
This is more of a question than an actual issue I think. However I was not able to find a solution on my own.
How do I `cd` into a directory that has a space in its name?
```
[/]>version
rmapi version: 0.0.12
[/]>ls
[f]	Quick sheets
[/]>cd Quick sheets
Error: directory doesn't exist
[/]>cd "Quick sheets"
Error: directory doesn't exist
[/]>cd Quick\ sheets
Error: directory doesn't exist
[/]>
```
Thanks

**Comment by elexx** [comment]
Nevermind. cd-ing into a file is a dumb idea.

**Comment by ddvk** [comment]
quote the directory, ie use “dir”
