### ISSUE TITLE
Return code is not set

### ISSUE THREAD

**Issue by andrewyates** [juruen/rmapi#14]
rmapi does not currently set an exit code, which makes it difficult to check whether a command succeeded when scripting.

```
$ go/bin/rmapi put file_does_not_exist     
ReMarkable Cloud API Shell
uploading: [file_does_not_exist]...
ERROR: 2018/03/29 10:54:56 zipdoc.go:27: failed to open source document file to read open file_does_not_exist: no such file or directory
ERROR: 2018/03/29 10:54:56 api.go:211: failed to create zip doc open file_does_not_exist: no such file or directory
Failed to upload file: %s open file_does_not_exist: no such file or directory

$ echo $?
0

$ go/bin/rmapi put some_file_that_does_exist
...

$ echo $?
0
```

Is it possible to exit with a non-zero code when an error is encountered, so that this can be checked for from within a calling script?

**Comment by juruen** [comment]
> Is it possible to exit with a non-zero code when an error is encountered, so that this can be checked for from within a calling script?

I'm not sure the library I use for the the interactive shell allows us to do this. I need to check. But it'd be definitely helpful for scripts.

**Comment by juruen** [comment]
> I'm not sure the library I use for the the interactive shell allows us to do this. I need to check. But it'd be definitely helpful for scripts.

So I just checked and we can definitely do it with single commands as in:

```
put foo
```

However, it's slightly more difficult to do it with pipelined commands:

```
echo -e "put foo\nls" | rmapi
```

But anyways, let's start with simple commands that I guess it's useful enough.

**Comment by andrewyates** [comment]
> But anyways, let's start with simple commands that I guess it's useful enough.

Yes, that satisfies my use case and would be great!

For pipelined commands, an ideal solution might be to add the `&&` operator and then set the exit code based on the last command to run. I'm content with only supporting single commands though.

**Comment by juruen** [comment]
@andrewyates 

I just added support to return exit code for non-interactive commands to master.

Let me know if that works for you!

**Comment by andrewyates** [comment]
It does, thanks!
