### ISSUE TITLE
Uploading rm files

### ISSUE THREAD

**Issue by qwert2003** [juruen/rmapi#143]
Feature request:
`put myNotes.rm`
rmapi would create a new notebook "myNotes" containing the uploaded page (rm file).

Background: I have added the reMarkable output type to my software [Drawj2d](https://drawj2d.sourceforge.io/) for technical line drawings. It writes a rm file. Transferring the file to the device using rmapi works, but it is tricky as it [requires several steps](https://sourceforge.net/p/drawj2d/blog/2020/12/drawj2d-115-released/#7ccf).

**Comment by qwert2003** [comment]
Ok, I have extended the drawj2d software (release 1.2.1). It is now able to generate a zip file (containing the drawing and the metadata files) in the format rMAPI expects: [wiki page](https://sourceforge.net/p/drawj2d/wiki/reMarkable)

Unfortunately I can't contribute code to rmapi, as I am not familiar with "go" (my [implementation](https://sourceforge.net/p/drawj2d/code/HEAD/tree/trunk/src/net/sf/jtikz/ReMarkableAPIzip.java) of "rm to zip" is in java).

In my opinion it would still be a nice feature extension for rmapi to be able to upload rm-files. Maybe even multiple files/pages into one notebook?

**Comment by ddvk** [comment]
yes, makes sense
