### ISSUE TITLE
Docker Image on Synology

### ISSUE THREAD

**Issue by neomorph77** [juruen/rmapi#144]
Hi, I found your project and I want to install the docker image on my Synology NAS in Docker.
Followed your description and you wrote:

`First clone this repository, then build a local container like

docker build -t rmapi .

**create the .config/rmapi config folder**

docker build -t rmapi .
`

When I start my container I get the following Error-Message:
`WARNING: 2020/12/30 10:16:36 config.go:46: failed to open /home/user/.rmapi with read /home/user/.rmapi: is a directory/n
`
Do you have any idea, what I have done wrong?

Thanks for reading
Patrick

**Comment by ddvk** [comment]
why docker? you can compile a armv5 binary

**Comment by neomorph77** [comment]
Thank you for your Information! Than I need a .spk file and have no idea how to compile it with your git and my Mac. Sorry for bad asking.

**Comment by ddvk** [comment]
GOARCH=arm go build
