### ISSUE TITLE
get full directory tree

### ISSUE THREAD

**Issue by VanDerLars** [juruen/rmapi#146]
There should be a way to get the full tree in one call.

Currently you need to get the list of sub directories and files within one directory folder by folder. Each call takes about 5 seconds mostly because of the web API latency.

So if you have a larger directory tree with like 10 or more (sub) directories, it takes about a minute or more to fetch all contents with the "ls" command.

Better would be a command which gives you the full tree of contents.

This should be possible with the API as described here:
https://github.com/splitbrain/ReMarkableAPI/wiki/Storage#listing-item-information

Would be a nice feature :)

**Comment by ddvk** [comment]
can't you do `find /`?

**Comment by ddvk** [comment]
we could add [f] and [d] as a prefix in the output of find?

**Comment by ddvk** [comment]
closing this as this as it was merged
