### ISSUE TITLE
Export *FULL* PDF with annotations

### ISSUE THREAD

**Issue by martin-braun** [juruen/rmapi#154]
The `geta` is my favorite command of this program. 

I started using my remarkable to sign contracts, when I sent them via mail in any case (otherwise I have to print, sign and scan everything). For this situation it would be helpful to export the annotations without stripping out pagers I haven't written on. 

For now I will export my PDF as PNG using the reMarkable app and then I will combine those to a new PDF, but it would be great to have this feature built into rmapi.

**Comment by ddvk** [comment]
there is an option for that `-a`

**Comment by martin-braun** [comment]
@ddvk Thanks, I had no idea. How can I learn about all possible options on all commands? `rmapi help` won't list them.

**Comment by michaelbeaumont** [comment]
@martin-braun `geta --help`

**Comment by martin-braun** [comment]
> `geta --help`

That doesn't work for any command, but it does work for `geta`, thanks.
