### ISSUE TITLE
Printing pdf-files directly to rM 

### ISSUE THREAD

**Issue by 0183-Mark** [juruen/rmapi#16]
I am new on this platform so my excuses if this is not the right place to post this question. After a succesfull installatio of the pluging  juruen made I tried to print a pdf-file from Adobe Acrobat. Without success. I got the message that printing is not able at the same time as saving. Is there a way to print directly from Adobe Acrobat to rM?

**Comment by ptman** [comment]
https://github.com/juruen/rmapi/blob/master/docs/tutorial-print-macosx.md - ?

**Comment by lobre** [comment]
@juruen, can we consider this as resolved/closed cause of inactivity?

**Comment by subutux** [comment]
if anyone is interested just found [these](https://github.com/ofosos/scratch/tree/master/remarkable-cups) working instructions.

**Comment by juruen** [comment]
I believe we can close this issue for now. If anyone disagree, please feel free to reopen it!
