### ISSUE TITLE
BUG: fails with non-ASCII characters in filename

### ISSUE THREAD

**Issue by Uzay-G** [juruen/rmapi#160]
Encountered an error when uploading a file with a non-ASCII filename:

```
[/]>put ./COURS_1_ENS_SC-élève.pdf
Error: Uknown rune: 233
[/]> 

```

Changing the name fixed this, just thought I should report this for other people with the same issue.

**Comment by ddvk** [comment]
you have to quote the name ege `"élève"`

**Comment by ddvk** [comment]
this should work now
