### ISSUE TITLE
"Failed to create a new user token"

### ISSUE THREAD

**Issue by RhvdG** [juruen/rmapi#166]
After working brilliantly for weeks, I am now presented with this error:

` ERROR: 2021/04/03 12:18:00 auth.go:99: failed to create a new user token `

**Comment by ddvk** [comment]
some more info, e.g which version and on what os you are running it?

**Comment by RhvdG** [comment]
> some more info, e.g which version and on what os you are running it?

I'm on macOS 11.2.3 (20D91).
I reinstalled rmapi yesterday to see if it would solve the problem, so I think I have the newest version.
If there's any queries you'd like me to run in Terminal.app, let me know.

**Comment by ddvk** [comment]
remove the rmapi.conf file, either in ~/ or in ~/Library/Application Support/rmapi/

**Comment by RhvdG** [comment]
Thanks, that worked. I looked for it only in ~/, before. The Print to Remarkable script now works fine, again, too.

**Comment by ddvk** [comment]
you sure it wasn't removed from the devices? (in my.remarakble.com web ui)?

**Comment by RhvdG** [comment]
It's possible that it was.

**Comment by ddvk** [comment]
ok, then closing this as solved
