### ISSUE TITLE
Build error: `licenseKey is not a function`

### ISSUE THREAD

**Issue by pkgw** [juruen/rmapi#176]
I'm trying to install rmapi on my Fedora 34 machine with:

```
GO111MODULE=on go get github.com/juruen/rmapi@latest
```

It fails with the error:

```
go/pkg/mod/github.com/juruen/rmapi@v0.0.14/annotations/license.go:10:3: error: licenseKey is not a function; ‘//go:linkname’ is only supported for functions
```

I don't really know anything about Go so my apologies if this is a silly error. My `go` is coming from the following OS package:

```
gcc-go                    x86_64               11.1.1-1.fc34
```

**Comment by ddvk** [comment]
what does `go version` print?
