### ISSUE TITLE
Failed to fetch document tree - 401 Unauthorized Error

### ISSUE THREAD

**Issue by peerdavid** [juruen/rmapi#177]
Hi,

if I execute ./rmapi I get ```failed to build documents tree, last error: failed to fetch document tree 401 Unauthorized Error```. I deleted the .rmapi file because I was not sure if my device token was still valid or not, but I still get the same error. Also, I have the same issue with other open-source tools (https://github.com/peerdavid/remapy) so I wonder if they changed the cloud API because the reMarkable android app and also the tablet still works fine...

Thanks a lot!
David

**Comment by stefanheyder** [comment]
I am experiencing the same issue; additionally I saw that when I deleted the `rmapi.config` the newly generated configuration has tokens that consist of html.

**Comment by peerdavid** [comment]
> I am experiencing the same issue; additionally I saw that when I deleted the `rmapi.config` the newly generated configuration has tokens that consist of html.

Same for me.

**Comment by iivvoo** [comment]
Same here. Previous rmapi.conf contained the token (eyJh....) and some html. Re-pairing results in no token and just the html. In both cases the html has `<title>reMarkable
  &bull; Device Activation</title>`

**Comment by ddvk** [comment]
the auth url has changed, I can push a fix

**Comment by ddvk** [comment]
so the url my.remarkable.com no longer points to their api

**Comment by ddvk** [comment]
I've merged this to master, so please get the latest version (it should ask for the one time code again)

**Comment by peerdavid** [comment]
Thank you so much for this very fast fix!

**Comment by ddvk** [comment]
@juruen we should create a new release probably

**Comment by juruen** [comment]
> @juruen we should create a new release probably

I'm  on it. Thanks a lot for the quick fix!

**Comment by juruen** [comment]
`0.0.15` is out with the auth fix.

**Comment by cfichtlscherer** [comment]
Thanks a lot for the fast fix!

**Comment by jasdev** [comment]
Just chiming in to say thanks for fixing this so quickly — y’all rock <3

**Comment by albertjmenkveld** [comment]
+1 from me.  Really impressed by how quickly and how will this was handled.  Keep up the great work.  :).

**Comment by juruen** [comment]
Thank you so much everyone for helping  (and cheering) on this one. 

The true hero is @ddvk who's been more than amazing at fixing and improving  this project for a long time now! Thank you! ❤️

**Comment by okflo** [comment]
so cool - many thanks for this fast fix! open source rules! :)

**Comment by vchryssos** [comment]
Is it possible that this issue is happening again? I am getting the same error, although I updated to the latest rmapi version.
