### ISSUE TITLE
URL for one-time code no longer correct

### ISSUE THREAD

**Issue by pkgw** [juruen/rmapi#182]
It looks like the URL to use to get a one-time code for `rmapi login` has changed. I can get a code here:

https://my.remarkable.com/device/connect/desktop

If I use the URL that 0.0.15 tells me:

https://my.remarkable.com/connect/desktop

I get a blank page, which was confusing me and making me think that maybe the reMarkable Cloud was having issues.

**Comment by justinlynn** [comment]
Confirmed here on my end as well.

**Comment by distefam** [comment]
The correct URL has changed again and is now: https://my.remarkable.com/device/desktop/connect
