### ISSUE TITLE
Store config in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ptman** [juruen/rmapi#19]
Please, instead of storing in $HOME, look at https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by ptman** [comment]
https://tip.golang.org/pkg/os/#UserCacheDir supports XDG spec, but there doesn't yet seem to be a similar method for Config directory in the stdlib

**Comment by ptman** [comment]
https://godoc.org/github.com/shibukawa/configdir seems decent

**Comment by torwag** [comment]
I would support this request as a change now is easier. As rmapi turns into be the best alternative for original desktop app, more and more projects rely on rmapi. If their installation scripts need to be changed as well, things get broken in multiple projects and ways.

**Comment by ptman** [comment]
https://golang.org/pkg/os/#UserConfigDir is now also in the stdlib (since 1.13)

**Comment by ddvk** [comment]
merged the code
