### ISSUE TITLE
can t connect using rmapi getting: panic:runtime error 

### ISSUE THREAD

**Issue by maro7777** [juruen/rmapi#193]
I need help here: getting following error trying to connect to rnfakecloud. With UI i can connect without problem:

Enter one-time code (go to https://my.remarkable.com/connect/desktop): pgvhqxwe
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x908ef0]

goroutine 1 [running]:
github.com/juruen/rmapi/transport.HttpClientCtx.addAuthorization(0xc000199770, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/rmapi/rmapi/transport/transport.go:62 +0x50
github.com/juruen/rmapi/transport.HttpClientCtx.Request(0xc000199770, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa41c60, 0x4, 0xc0002d1fb0, 0x2b, ...)
	/home/runner/work/rmapi/rmapi/transport/transport.go:168 +0x10f
github.com/juruen/rmapi/transport.HttpClientCtx.httpRawReq(0xc000199770, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa41c60, 0x4, 0xc0002d1fb0, 0x2b, ...)
	/home/runner/work/rmapi/rmapi/transport/transport.go:130 +0x198
github.com/juruen/rmapi/transport.HttpClientCtx.Post(...)
	/home/runner/work/rmapi/rmapi/transport/transport.go:98
github.com/juruen/rmapi/api.newDeviceToken(0xc000199740, 0xc0002dd1e3, 0x8, 0x0, 0x0, 0x0, 0xc0001996e0)
	/home/runner/work/rmapi/rmapi/api/auth.go:90 +0x233
github.com/juruen/rmapi/api.AuthHttpCtx(0xc000070000, 0xc0000201d0)
	/home/runner/work/rmapi/rmapi/api/auth.go:29 +0x1e9
main.main()
	/home/runner/work/rmapi/rmapi/main.go:32 +0x193

**Comment by ddvk** [comment]
you have to set both env variables, RMAPI_DOC and RMAPI_AUTH to the same url.

also make sure the url is not malformed, e.g. `https://  some space`

**Comment by maro7777** [comment]
sorry i am not a coder but a beginner learning linux and so on. So maybe my understanding does sometimes stand in my way. 

The var. were malformed. 
but know i get this:
Trace: 2021/07/13 21:31:59 transport.go:173: request: POST /token/json/2/device/new HTTP/1.1
Host: ******.com:3000
Authorization: Bearer
User-Agent: rmapi

{"code":"smabvles","deviceDesc":"desktop-linux","deviceID":"440f791f-e782-48c4-ba9c-3d28cf2d739a"} <nil>
ERROR: 2021/07/13 21:31:59 transport.go:179: http request failed with Post "https://****.com:3000/token/json/2/device/new": http: server gave HTTP response to HTTPS client
ERROR: 2021/07/13 21:31:59 auth.go:93: failed to create a new device token

i do not understand that. Could you please clarify . thanks

**Comment by ddvk** [comment]
the server is running with tls (https), the url you should use is http://server

check the rmfakecloud docu for how to run it with https

this does not concern rmapi, open an issuse in rmfakecloud

**Comment by maro7777** [comment]
ok i see , i will close that here and open an issue on rmfakecloud
