### ISSUE TITLE
files not showing up in cloud

### ISSUE THREAD

**Issue by aqwzs** [juruen/rmapi#199]
I can successfully run every command and when I upload a pdf file, it says "OK" but then the file doesn't show up in the cloud, using `ls` shows the file correctly. When I use `stat` it shows `"Success": false,` and I don't know what it supposed to mean because all other files have it set as true, after some time the new files also have true but they still don't show up in the app nor on the remarkable.
I'm on version 0.0.15 of rmapi

**Comment by michalfrankl** [comment]
I seem to have the same problem, starting with yesterday...

**Comment by dariusk** [comment]
It's related to the new version of the cloud API. Customers are being switched to the new API in the background without telling them, and it causes this issue where rmapi says it's uploaded something but it's not actually there. More info here: https://github.com/juruen/rmapi/issues/187

**Comment by aqwzs** [comment]
So there's no solution to this?

**Comment by juruen** [comment]
@aqwzs l just checked. my account hasn't been migrated  to the new API yet so I can't  reverse engineer the API to add support for it.

Once that happens, if I have some time, I'll definitely do it. Or if anyone can point me  to an implementation of the new API I could start working with that.

**Comment by ddvk** [comment]
dupcliate of #187
