### ISSUE TITLE
Unable to retrieve user token

### ISSUE THREAD

**Issue by TilBlechschmidt** [juruen/rmapi#2]
I am unable to retrieve the user token from the API.
In order deviceBearer, newUserDevice, resp, err:
```
ERROR: 2018/02/21 15:58:48 auth.go:89: 1
ERROR: 2018/02/21 15:58:48 auth.go:90: https://my.remarkable.com/token/user/new
ERROR: 2018/02/21 15:58:48 auth.go:91: {}
ERROR: 2018/02/21 15:58:48 auth.go:92: request failed with status %!i(int=403)
ERROR: 2018/02/21 15:58:48 auth.go:94: failed to create a new user token
```

**Comment by TheMegaTB** [comment]
The only direct difference to the [PHP](https://github.com/splitbrain/ReMarkableAPI/blob/master/src/RemarkableAPI.php#L69) client for the same API endpoint that is immediately obvious is the `deviceDesc` which is `desktop-windows` instead of `desktop-linux`.

**Comment by juruen** [comment]
@TheMegaTB Yup, I had broken the auth code. I hardly exercised it because I have my user token in my config file already.

Please, try again with current version. It should work now. I tested it from scratch. You may need to delete `.rmapi` from your home directory if it keeps failing.

Let me know if it works now!

**Comment by TheMegaTB** [comment]
Worked perfectly thank you.
Although the first time I launch the program I get a `401` error which is gone on consecutive launches:
```
ERROR: 2018/02/22 10:24:23 api.go:31: failed to fetch documents %s 401 Unauthorized Error
ERROR: 2018/02/22 10:24:23 main.go:19: retrying...
```

**Comment by Mehechiger** [comment]
@juruen Being constantly unable to connect too...

`bogon:~ patton$ /Users/Patton/go/bin/rmapi
ERROR: 2018/02/23 14:09:04 transport.go:174: http request failed with%!(EXTRA *url.Error=Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 69.171.245.49:443: i/o timeout)
ERROR: 2018/02/23 14:09:04 api.go:31: failed to fetch documents %s Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 69.171.245.49:443: i/o timeout
ERROR: 2018/02/23 14:09:04 main.go:19: retrying...
ERROR: 2018/02/23 14:09:34 transport.go:174: http request failed with%!(EXTRA *url.Error=Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 208.101.60.87:443: i/o timeout)
ERROR: 2018/02/23 14:09:34 api.go:31: failed to fetch documents %s Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 208.101.60.87:443: i/o timeout
ERROR: 2018/02/23 14:09:34 main.go:19: retrying...
ERROR: 2018/02/23 14:10:05 transport.go:174: http request failed with%!(EXTRA *url.Error=Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 208.101.60.87:443: i/o timeout)
ERROR: 2018/02/23 14:10:05 api.go:31: failed to fetch documents %s Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 208.101.60.87:443: i/o timeout
ERROR: 2018/02/23 14:10:05 main.go:19: retrying...
ERROR: 2018/02/23 14:10:05 main.go:24: failed to build documents tree`

**Comment by juruen** [comment]
@TheMegaTB,

> Although the first time I launch the program I get a 401 error which is gone on consecutive launches:

Yeah, that part of the code needs some love.

**Comment by juruen** [comment]
@Mehechiger 

> ERROR: 2018/02/23 14:09:04 api.go:31: failed to fetch documents %s Get https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs: dial tcp 

It seems it's timing out trying to connect to `https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs`.

Are you using any sort of proxy?

Anyway, could you try again, and if it fails, could you post the output of:

```
time curl -v https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs
```

Thank you!

**Comment by Mehechiger** [comment]
@juruen Yep I'm in China so proxy is necessary to access anything that is google based... and I'm using a SSR proxy. However no matter I turn it on or off, the rmapi just can't get through. I've tried to ping the server too but failed. Yet any other google service is still accessible. Strange.
And here's the result to the time curl:
*   Trying 69.63.184.142...
* TCP_NODELAY set
* Connection failed
* connect to 69.63.184.142 port 443 failed: Operation timed out
* Failed to connect to document-storage-production-dot-remarkable-production.appspot.com port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to document-storage-production-dot-remarkable-production.appspot.com port 443: Operation timed out

real	1m15.320s
user	0m0.011s
sys	0m0.020s

**Comment by ddvk** [comment]
i'm closing this as I don't think we can do anything about it.  
go supports https and socks5 proxies, e.g:
```
ssh -D 2000 somehostwithaccess
https_proxy=socks5://localhost:2000 rmapi ls
```
