### ISSUE TITLE
Incremental sync

### ISSUE THREAD

**Issue by ptman** [juruen/rmapi#20]
Is it possible to get all files incrementally, i.e. only get files that aren't already downloaded? Like rclone or rsync. Would make it much nicer to user for backup

**Comment by torwag** [comment]
I think there is no need to save the metadata but just the last time it was synced. With the metadata of the file on the server side you would have to skip files which was not changed since the last sync. 
That said, this would only be a one way sync... for two-way stuff gets more complex

**Comment by ptman** [comment]
Excellent! Are old files removed? I didn't see any unlink calls

**Comment by ddvk** [comment]
ah, forgot to implement the flag, currently deleted/moved files don't get removed

**Comment by torwag** [comment]
Make it an option as there are scenarios where people would like to keep deleted files e.g. for simple backups.
Whatever now as we have incremental sync. More sophisticated backup scenarios should be possible. Maybe time for a rmapi-backup script with an rotating incremental current/daily, weekly, monthly backup scheme. As for this, as long as rmapi feeds a mirror of the rM on the host disk, I think one could utilise one of the common backup tools which work on block level for even smaller incremental backups.

**Comment by ddvk** [comment]
it is an option, (-d) just does nothing atm

**Comment by ddvk** [comment]
ok, i think i fixed it

**Comment by tbabej** [comment]
Shouldn't incremental sync be the default? I was surprised to learn I have to switch on the `-i` flag.

**Comment by ddvk** [comment]
> Shouldn't incremental sync be the default? I was surprised to learn I have to switch on the `-i` flag.

i didn't want to change the current behaviour on which some users may depend or expect, so it is opt in (also removing deleted files) .  if it turns out that it works well and others agree, i have nothing against making it the default.
