### ISSUE TITLE
Naming of .rm files based on page index instead of UUID

### ISSUE THREAD

**Issue by skius** [juruen/rmapi#201]
On my reMarkable 2 (OS 2.9) the `.rm` files of an annotated PDF are based on UUIDs:
```
reMarkable: ~/.local/share/remarkable/xochitl/ ls 1497410a-186c-11ec-9354-00155dfe4175
3cf3b23c-3a7c-4126-a548-e3ee58e0bff5-metadata.json  40db70b9-74e0-4405-98e5-dd1204d57b0f-metadata.json
3cf3b23c-3a7c-4126-a548-e3ee58e0bff5.rm             40db70b9-74e0-4405-98e5-dd1204d57b0f.rm
```

However, downloading that document using `rmapi` gets me page index based files:
```
> $ ls 1497410a-186c-11ec-9354-00155dfe4175/
0-metadata.json  0.rm  1-metadata.json  1.rm
```

Is it possible to download and upload docs that use the UUID naming scheme for `.rm` files? They are the same UUIDs that appear in the top-level `.content` JSON under `pages:`. 
Example: if `1.rm` is a file that `rmapi` downloads, then on the tablet that file is named `{pages[1]}.rm`.

___

I stumbled across this, because I ran into an issue when trying to insert a blank page into an annotated PDF, where annotations would be duplicated on the newly inserted page. Originally, I had a PDF with two pages (1 and 2, 1-indexed) with annotations on both of them. I then wanted to insert a blank page between page 1 and page 2, which I did as follows:

Original `.zip` (downloaded with `rmapi`):
```
docUUID/0.rm
docUUID/0-metadata.json
docUUID/1.rm
docUUID/1-metadata.json
docUUID.pages
docUUID.content
docUUID.pdf
```
Edited `.zip` to include a fresh page between pages 1 and 2:
```
docUUID/0.rm
docUUID/0-metadata.json
docUUID/2.rm            (== old 1.rm)
docUUID/2-metadata.json (== old 1-metadata.json)
docUUID.pages'
docUUID.content'
docUUID.pdf'
```
where `docUUID.pages'` has an additional line "Blank" for the template that the new page uses,
where `docUUID.content'` has a new page UUID entry in the pages array at index 1,
where `docUUID.pdf'` has a blank page inserted between page 1 and page 2.

This, however, lead to the new document, as seen on the reMarkable, to look as follows:
```
page 1: original PDF page 1 + original annotations for page 1
page 2: blank inserted page + original annotations for page 2
page 3: original PDF page 2 + original annotations for page 2
```

I was able to resolve this issue (the annotations on the fresh PDF page) by deleting the whole `pages` array from `docUUID.content'` (thanks @ddvk!), however I think it's still worth to allow users to directly download and use UUID'd `.rm` files, such that use-cases like mine are more easily resolvable.

___

If the reMarkable cloud does not expose the UUID files, a workaround could be made, where the `x.rm` and ` x-metadata.json` (page index based) files are simply dynamically rewritten to `{pages[x]}.rm` and `{pages[x]}-metadata.json`.

**Comment by ddvk** [comment]
this is a bit complicated, rmapi doesnt do anything with the zip and expects this format, also the tablet expects it probaly.

What happens is this:
The tablet changes the file names before uploading, thus creating a .zip with (01.rm,02.rm,... files)
When the same zip is received by the tablet, it creates the pages based on the `pages:[]` tag in the `.content` file

i think the solutions is: 
- rename all pages after the inserted page
- create the page
- add a random uuid in the `pages:[]` array at the index of the new page

**Comment by skius** [comment]
@ddvk If I understand your proposed solution correctly, it is exactly what I describe in the 2nd section of my original post. Sadly that approach does not work, and leads to the weird behaviour I mentioned:

```
page 1: original PDF page 1 + original annotations for page 1
page 2: blank inserted page + original annotations for page 2
page 3: original PDF page 2 + original annotations for page 2
```

You should see that behavior if you uncomment this block of code in library: https://github.com/skius/rm-pdf-tools/blob/master/run.go#L176

**Comment by ddvk** [comment]
it seems to work on my machine. either a page was duplicated or already existed

**Comment by skius** [comment]
Thanks. I must've fixed this somehow in the meantime and didn't realize. I'm closing the issue for now.
