### ISSUE TITLE
Two clouds?

### ISSUE THREAD

**Issue by wiktor-obrebski** [juruen/rmapi#206]
Currently, when I use rmapi the files I see are different than on my device.
I can download/upload the files like always with rmapi.
But they do not appear on my device.

On the other hand, when I use the default remarkable Windows client, it shows me proper files (these I have on my ReMarkable device). And when I uploaded something by the client, it appeared on my device.

I am confused. Is this possible that it's some issues with the new "Connect" feature, some kind of migration to another cloud?

https://remarkable.com/store/connect

**Comment by ddvk** [comment]
there is a pr implementing the. ew cloud sync
