### ISSUE TITLE
[sync15] zip-uploads to subfolders

### ISSUE THREAD

**Issue by qwert2003** [juruen/rmapi#216]
Minor issue:
A notebook (zip) uploaded to a subfolder by rMAPI
- appears at the right place on the device
- but is listed in the root folder by rMAPI.

Example

```
> rmapi
Refreshing tree...
WARNING!!!
  Using the new 1.5 sync, this has not been fully tested yet!!!
  Make sure you have a backup, in case there is a bug that could cause data loss!
ReMarkable Cloud API Shell
[/]>cd Projects
[/Projects]>put test.zip
uploading: [test.zip]...OK
[/Projects]>exit
> rmapi
Refreshing tree...
WARNING!!!
  Using the new 1.5 sync, this has not been fully tested yet!!!
  Make sure you have a backup, in case there is a bug that could cause data loss!
ReMarkable Cloud API Shell
[/]>ls
[CUT]
[f]     test
[CUT]
[/]>cd Projects/

[/Projects]>ls
[test IS MISSING]
[/Projects]>
```

**Comment by qwert2003** [comment]
By the way (related minor issue):
After uploading when I sort by "Last updated", the notebook does not appear at the first place.

**Comment by qwert2003** [comment]
@ddvk I see you have made commits to your sync15 branch. Is it work in progress or ready to test?

**Comment by ddvk** [comment]
ready to test

**Comment by ddvk** [comment]
forgot to merge

**Comment by qwert2003** [comment]
Tested (using ddvk/rmapi/tree/sync15):
Uploading to a subfolder seems to work properly. Rmapi lists the notebook in the expected subfolder.
Thanks!
