### ISSUE TITLE
I get many upload errors when running mput with a large directory of files

### ISSUE THREAD

**Issue by japhir** [juruen/rmapi#225]
Trying to upload all of my PDFs for papers to read, I get the following warning after about 5 successful uploads:

```
ERROR: 2022/01/27 09:41:40 apictx.go:218: cannot send sync request failed with status 429
```

This appears to be a "too many requests" type error.

Once I see this, I get the same warning for many (all?) subsequent files it tries to upload.

**Comment by ddvk** [comment]
their api has a rate limiting, this shoud fix it

**Comment by juruen** [comment]
@ddvk fix is now merged and shipped.

Thank you all!
