### ISSUE TITLE
Windows binary lacks suffix .exe

### ISSUE THREAD

**Issue by qwert2003** [juruen/rmapi#228]
The release page contains binaries for various OS (thanks!). The download file for Windows *rmapi-win64.zip* contains the program *rmapi*. In order to run the program it has to be renamed to *rmapi.exe*.

This might not be obvious for many users.
If there is a reason to omit the suffix (anti-virus scanners?) a hint in the README section Binary could be helpful.

**Comment by juruen** [comment]
@qwert2003 thank you for the heads-up. I just uploaded a new zip with the right extension.

**Comment by Mikowmer** [comment]
Reopening this because the 0.0.23 release is once more missing the .exe file extension.

**Comment by juruen** [comment]
@Mikowmer I believe the latest changes I merged into master should fix this for good.
