### ISSUE TITLE
IDEA: Support for multiple devices, concurrently

### ISSUE THREAD

**Issue by xxxserxxx** [juruen/rmapi#229]
I have a use case: my wife and I both have Remarkables and frequently want to share documents. PDFs, notebooks, what have you. In an ideal world, the tablet itself would have a "share" option by which you could send a Remarkable document, in the proprietary source format, to another Remarkable account, or device.

Since this is not supported, I'm wondering if rmapi could function as a work-around.  It'd need to authorize both accounts and persist both tokens, and a new function would copy from one cloud storage to another.

Does this sound interesting? Do you know of a reason why this wouldn't work? If it's something you might eventually merge, I can investigate the changes and submit a pull request.

**Comment by ddvk** [comment]
you can create two scripts with different configs, then you can just do `myscript1.sh get file; myscript2.sh put file.zip` e.g.
```bash
#!/bin/sh
export RMAPI_CONFIG=~/.rmapi.rm1
rmapi "$@"
```

**Comment by xxxserxxx** [comment]
Good enough for government work.
