### ISSUE TITLE
Add optional path to `ls` command

### ISSUE THREAD

**Issue by dbosk** [juruen/rmapi#26]
The `ls` command only lists the files in the current directory. This means that we can only list contents of the root directory from the command line, from where it would actually be interesting to specify a path to a directory to list the contents of.

**Comment by rudbast** [comment]
@dbosk i've added a PR for this, but am unable to test it, think you can try checkout my branch and test it ?

**Comment by juruen** [comment]
> @dbosk i've added a PR for this, but am unable to test it, think you can try checkout my branch and test it ?

@rudbast  wow, I'm really sorry, I just literally pushed an implementation for this :( Let me at least take a look at your PR.

I would've loved to merge yours.

**Comment by juruen** [comment]
@rudbast It was pretty much the same implementation  would've worked perfectly!

**Comment by rudbast** [comment]
no problem :+1: glad to help, or not :smile:

**Comment by oscarmorrison** [comment]
Hi @juruen @rudbast did this break?

![image](https://user-images.githubusercontent.com/1651212/60409481-2ae70c80-9c07-11e9-877d-c5e2e4829efe.png)
I cant get it to list files in a sub directory.

What is displayed is at the root dir, I want to see files in `/Zotero`

**Comment by juruen** [comment]
@oscarmorrison, it seems to be an 0.4 issue.

`master` seems to work fine:

```
rmapi juruen$ ./rmapi ls /Math
ReMarkable Cloud API Shell
[f]	math_for_deep_learning
[d]	statistics
[d]	Probability
```

**Comment by oscarmorrison** [comment]
Yes @juruen verified working in .4
