### ISSUE TITLE
Client timeout for large files

### ISSUE THREAD

**Issue by peerdavid** [juruen/rmapi#28]
I'm running into a timeout when I try to upload a pdf file with 30MB: 
```
[/]>put large.pdf
uploading: [large.pdf]...ERROR: 2018/10/02 17:22:02 transport.go:174: http request failed with [...] net/http: request canceled (Client.Timeout exceeded while awaiting headers))
```

Is it possible to increase the timeout -> I think its currently 60 seconds right?
```
var httpClient = &http.Client{Timeout: 60 * time.Second}
```

**Comment by juruen** [comment]
@peerdavid did you try to increase the timeout yourself to see if that does the trick?
