### ISSUE TITLE
Authorization fails

### ISSUE THREAD

**Issue by maximiliankir** [juruen/rmapi#284]
When I start rmapi, using the binaries from the latest release, I get the following error messages:

```
$ ./rmapi 
ERROR: 2022/12/28 12:39:50 transport.go:184: http request failed with Post "https://webapp-prod.cloud.remarkable.engineering/token/json/2/user/new": net/http: invalid header field value "Bearer <!doctype html><html><head><meta charset=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1,maximum-scale=1\"/><title>reMarkable</title><script>(function (w, d, s, l, i) {\n        w[l] = w[l] || [];\n        w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });\n        var f = d.getElementsByTagName(s)[0],\n          j = d.createElement(s),\n          dl = l != 'dataLayer' ? '&l=' + l : '';\n        j.async = true;\n        j.src =\n          'https://www.googletagmanager.com/gtm.js?id=' +\n          i +\n          dl +\n          '&gtm_auth=yiAE5UBHo4MnklcN9MmJBA&gtm_preview=env-1&gtm_cookies_win=x';\n        f.parentNode.insertBefore(j, f);\n      })(window, document, 'script', 'dataLayer', 'GTM-MKR4CS8');</script><link rel=\"icon\" type=\"image/x-icon\" href=\"/assets/favicon.ico\"><link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/assets/favicon-16x16.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/assets/favicon-32x32.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"48x48\" href=\"/assets/favicon-48x48.png\"><link rel=\"manifest\" href=\"/assets/manifest.webmanifest\"><meta name=\"mobile-web-app-capable\" content=\"yes\"><meta name=\"theme-color\" content=\"#fff\"><meta name=\"application-name\" content=\"cloud-webapp-frontend\"><link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/assets/apple-touch-icon-57x57.png\"><link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/assets/apple-touch-icon-60x60.png\"><link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/assets/apple-touch-icon-72x72.png\"><link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/assets/apple-touch-icon-76x76.png\"><link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/assets/apple-touch-icon-114x114.png\"><link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/assets/apple-touch-icon-120x120.png\"><link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/assets/apple-touch-icon-144x144.png\"><link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/assets/apple-touch-icon-152x152.png\"><link rel=\"apple-touch-icon\" sizes=\"167x167\" href=\"/assets/apple-touch-icon-167x167.png\"><link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/assets/apple-touch-icon-180x180.png\"><link rel=\"apple-touch-icon\" sizes=\"1024x1024\" href=\"/assets/apple-touch-icon-1024x1024.png\"><meta name=\"apple-mobile-web-app-capable\" content=\"yes\"><meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\"><meta name=\"apple-mobile-web-app-title\" content=\"cloud-webapp-frontend\"><meta name=\"msapplication-TileColor\" content=\"#fff\"><meta name=\"msapplication-TileImage\" content=\"/assets/mstile-144x144.png\"><meta name=\"msapplication-config\" content=\"/assets/browserconfig.xml\"><script defer=\"defer\" src=\"/app-4625c991a28eb276dd24.js\"></script><link href=\"/app-38710d8c3ce3f7ceb000.css\" rel=\"stylesheet\"></head><body id=\"body\"><noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-MKR4CS8&gtm_auth=yiAE5UBHo4MnklcN9MmJBA&gtm_preview=env-1&gtm_cookies_win=x\" height=\"0\" width=\"0\" style=\"display: none; visibility: hidden\"></iframe></noscript><div id=\"header\"></div><div id=\"root\"></div><div id=\"footer\"></div></body></html>" for key Authorization
ERROR: 2022/12/28 12:39:50 auth.go:50: failed to create user token from device token Post "https://webapp-prod.cloud.remarkable.engineering/token/json/2/user/new": net/http: invalid header field value "Bearer <!doctype html><html><head><meta charset=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1,maximum-scale=1\"/><title>reMarkable</title><script>(function (w, d, s, l, i) {\n        w[l] = w[l] || [];\n        w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });\n        var f = d.getElementsByTagName(s)[0],\n          j = d.createElement(s),\n          dl = l != 'dataLayer' ? '&l=' + l : '';\n        j.async = true;\n        j.src =\n          'https://www.googletagmanager.com/gtm.js?id=' +\n          i +\n          dl +\n          '&gtm_auth=yiAE5UBHo4MnklcN9MmJBA&gtm_preview=env-1&gtm_cookies_win=x';\n        f.parentNode.insertBefore(j, f);\n      })(window, document, 'script', 'dataLayer', 'GTM-MKR4CS8');</script><link rel=\"icon\" type=\"image/x-icon\" href=\"/assets/favicon.ico\"><link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/assets/favicon-16x16.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/assets/favicon-32x32.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"48x48\" href=\"/assets/favicon-48x48.png\"><link rel=\"manifest\" href=\"/assets/manifest.webmanifest\"><meta name=\"mobile-web-app-capable\" content=\"yes\"><meta name=\"theme-color\" content=\"#fff\"><meta name=\"application-name\" content=\"cloud-webapp-frontend\"><link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/assets/apple-touch-icon-57x57.png\"><link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/assets/apple-touch-icon-60x60.png\"><link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/assets/apple-touch-icon-72x72.png\"><link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/assets/apple-touch-icon-76x76.png\"><link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/assets/apple-touch-icon-114x114.png\"><link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/assets/apple-touch-icon-120x120.png\"><link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/assets/apple-touch-icon-144x144.png\"><link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/assets/apple-touch-icon-152x152.png\"><link rel=\"apple-touch-icon\" sizes=\"167x167\" href=\"/assets/apple-touch-icon-167x167.png\"><link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/assets/apple-touch-icon-180x180.png\"><link rel=\"apple-touch-icon\" sizes=\"1024x1024\" href=\"/assets/apple-touch-icon-1024x1024.png\"><meta name=\"apple-mobile-web-app-capable\" content=\"yes\"><meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\"><meta name=\"apple-mobile-web-app-title\" content=\"cloud-webapp-frontend\"><meta name=\"msapplication-TileColor\" content=\"#fff\"><meta name=\"msapplication-TileImage\" content=\"/assets/mstile-144x144.png\"><meta name=\"msapplication-config\" content=\"/assets/browserconfig.xml\"><script defer=\"defer\" src=\"/app-4625c991a28eb276dd24.js\"></script><link href=\"/app-38710d8c3ce3f7ceb000.css\" rel=\"stylesheet\"></head><body id=\"body\"><noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-MKR4CS8&gtm_auth=yiAE5UBHo4MnklcN9MmJBA&gtm_preview=env-1&gtm_cookies_win=x\" height=\"0\" width=\"0\" style=\"display: none; visibility: hidden\"></iframe></noscript><div id=\"header\"></div><div id=\"root\"></div><div id=\"footer\"></div></body></html>" for key Authorization

```

It seams like retrieval of device token and user token is not working anymore.

**Comment by ddvk** [comment]
do a `rmapi reset` and then try reconnecting again

**Comment by opie4624** [comment]
I have the same issue. After doing a reset:
```
ERROR: 2022/12/29 19:22:42 auth.go:93: failed to create a new device token
```

**Comment by pako-github** [comment]
If I set RMAPI_TRACE = 1 I receive the following error message as response from the server:

<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>

**Comment by maximiliankir** [comment]
`rmapi reset` did the trick for me. But can someone please explain, what the problem was there? I used freshly downloaded rmapi binaries.

Actually I had and still have authentication problems with the rmapy library. To further debug this problem I tried rmapi. Now that it magically works after a reset, I didn't make any progress.

**Comment by ddvk** [comment]
> `rmapi reset` did the trick for me. But can someone please explain, what the problem was there? I used freshly downloaded rmapi binaries.
> 
> 
> 
> Actually I had and still have authentication problems with the rmapy library. To further debug this problem I tried rmapi. Now that it magically works after a reset, I didn't make any progress.

rmapi had a 200 response, but because the url was wrong it got just html for a token, which then didnt work

**Comment by pako-github** [comment]
> `rmapi reset` did the trick for me. But can someone please explain, what the problem was there? I used freshly downloaded rmapi binaries.
> 
> Actually I had and still have authentication problems with the rmapy library. To further debug this problem I tried rmapi. Now that it magically works after a reset, I didn't make any progress.

Unfortunately `rmapi reset` did not solve my problem.

**Comment by ddvk** [comment]
> > `rmapi reset` did the trick for me. But can someone please explain, what the problem was there? I used freshly downloaded rmapi binaries.
> > Actually I had and still have authentication problems with the rmapy library. To further debug this problem I tried rmapi. Now that it magically works after a reset, I didn't make any progress.
> 
> Unfortunately `rmapi reset` did not solve my problem.

what version of rmapi are you using? what is the url that fails with 500?

**Comment by pako-github** [comment]
I use the latest commit. Here is the log (I removed the Authorization Bearer)
`
Refreshing tree...
Trace: 2023/01/01 13:27:51 blobstorage.go:35: fetching GET blob url for: root
Trace: 2023/01/01 13:27:51 transport.go:177: request: POST /api/v1/signed-urls/downloads HTTP/1.1
Host: rm-blob-storage-prod.appspot.com
User-Agent: rmapi

{"http_method":"GET","relative_path":"root"} <nil>
Trace: 2023/01/01 13:27:52 transport.go:190: HTTP/2.0 401 Unauthorized
Content-Length: 14
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Type: text/plain; charset=utf-8
Date: Sun, 01 Jan 2023 12:27:52 GMT
Server: Google Frontend
X-Cloud-Trace-Context: d0c90c0c7f592c9578e89c783a90f4bc;o=1
X-Content-Type-Options: nosniff

invalid token
 <nil>
Trace: 2023/01/01 13:27:52 transport.go:194: request failed with status 401
Trace: 2023/01/01 13:27:52 main.go:38: 401 Unauthorized Error
Trace: 2023/01/01 13:27:52 transport.go:177: request: POST /token/json/2/user/new HTTP/1.1
Host: webapp-production-dot-remarkable-production.appspot.com
User-Agent: rmapi

 <nil>
Trace: 2023/01/01 13:27:52 transport.go:190: HTTP/2.0 500 Internal Server Error
Content-Length: 323
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Type: text/html; charset=UTF-8
Date: Sun, 01 Jan 2023 12:27:52 GMT
Server: Google Frontend


<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
 <nil>
Trace: 2023/01/01 13:27:52 transport.go:194: request failed with status 500
ERROR: 2023/01/01 13:27:52 auth.go:50: failed to create user token from device token request failed with status 500
`

**Comment by ddvk** [comment]
should work now.

make sure there is no old rmapi version somewhere in your PATH.
