### ISSUE TITLE
Permanent deletion and reverting of files in the cloud

### ISSUE THREAD

**Issue by evavh** [juruen/rmapi#285]
I've recently run into quite a severe issue with my reMarkable. Some files and folders get reverted to previous, usually day-old versions, and some get downright deleted from both the device and the cloud.

I have been in contact with reMarkable support about this, and they seem to be taking this issue very seriously. Today I had the issue appear (an entire folder of notes got deleted, in fact) right when I uploaded some files through rmapi, without having touched any other official or third-party tool. I therefore think there is something going wrong on both ends, both with the reMarkable cloud and with rmapi.

The issue started when the broken sync was recently fixed in 0.0.23. I have a whole e-mail chain of reporting on it that I could share if that would help (bit too much to post here).

**Comment by ddvk** [comment]
can you give some info and examples, how exactly you uploaded the files: e.g. 
 put,mput `rmapi put somefile` or rmapi, then put.
 uploading the files in root, subfolder,etc
 what is you xochitl's version
a lot of changes went into the last version (besides the url change), so there maybe something there.

**Comment by harryderouich** [comment]
Just realising that this has perhaps happened to me too. Day before yesterday I had a file rolled back to an earlier version, didn't think too much of it but today lost an entire folder.

**Comment by ddvk** [comment]
#if that happens on the device, can you make a copy of the rmapi .cache file before running rmapi. then check whether the missing folder is in the file

**Comment by harryderouich** [comment]
Sorry to have to ask, how do I access that if I'm using the extracted rmapi-linuxx86-64.tar.gz?

**Comment by evavh** [comment]
In my case it last happened when uploading multiple files with a rmapi put command (in a script), but I have had it happen when I had recently uploaded a single file using rmapi put.
I always upload in the root folder.
My xochitl version is 2.15.1.1189.

**Comment by ddvk** [comment]
under linux the file is in: ~/.cache/rmapi/.tree

iirc

**Comment by ddvk** [comment]
so there is a pull request wich can dump/version the cache fiels and root indexes which would help pinpoint the problem.
can you build the pull request and set `RMAPI_DUMPPATH=/some/folder` so that everytime rmapi is run the files are saved.

**Comment by evavh** [comment]
I just uploaded a file using rmapi put, and the issue occurred. How can I get the dumps to you @ddvk?

**Comment by ddvk** [comment]
> I just uploaded a file using rmapi put, and the issue occurred. How can I get the dumps to you @ddvk?

you uaed the pull request?
probably come to discord

**Comment by ddvk** [comment]
try version 0.0.25

**Comment by evavh** [comment]
I haven't had the issue reoccur with version 0.0.25, so it seems fixed.
