### ISSUE TITLE
Can print to RM from Preview; not from Safari

### ISSUE THREAD

**Issue by sshiva01** [juruen/rmapi#291]
As the title says, I'm able to open a pdf in Preview and print-to-remarkable. However, when I do the same thing in Safari -- i.e. print a pdf (from reader mode) within Safari -- nothing happens, and the documents never show up on the device. I'm not too code-savvy, so I downloaded the most recent MacOS v0.0.25 from the "Releases" page, and followed the instructions on the tutorial for printing directly to the RM. Is this a bug, or am I doing something wrong?

And I'm on v3.1 (beta) of the RM software.

**Comment by ddvk** [comment]
you're doing something wrong. rmapi just uploads the file tomthe cloud, soprobably something with the scripts / automator is not right

**Comment by sshiva01** [comment]
Thanks, I tried reseting the whole setup. I've now found that I can print to RM directly from Safari -- except for when I print an article being viewed in reader mode. Perhaps that's a Safari issue.
