### ISSUE TITLE
mget command only gets directories

### ISSUE THREAD

**Issue by GjjvdBurg** [juruen/rmapi#3]
Great tool, thanks a lot for making this!

I'm trying to use the `mget` command to download all the files, but I only seem to get the directories. No errors occur and each file does get a line stating it was downloaded okay:

    downloading [./Quick sheets]... OK

However, after the processes finishes, I only have the directory structure, not the files. (I checked, but they're not hidden either). Any thoughts?

**Comment by juruen** [comment]
Hi @GjjvdBurg 

> I'm trying to use the mget command to download all the files, but I only seem to get the directories. No errors occur and each file does get a line stating it was downloaded okay:

Which operating system are you using? I'm testing on Mac. In any case, when I download the files, I don't add the `.zip` extension to them. Could that be the case and you think that you are only seeing directories?

In any case, I'm going to add `.zip` extension to the downloaded files to make it more clear.

**Comment by GjjvdBurg** [comment]
Hi @juruen,

I'm on Arch Linux. Unfortunately it doesn't seem to be the `.zip` extension. There just aren't any files in the directory structure. After running `mget` I can for instance run `find . -type f`, but I get no results.

Let me know if there's anything I can try to help sort this out!

**Comment by juruen** [comment]
> I'm on Arch Linux. Unfortunately it doesn't seem to be the .zip extension. There just aren't any files in the directory structure. After running mget I can for instance run find . -type f, but I get no results.

I'm going to try on Ubuntu. Could you also tell me which Arch Linux and Go version are you using?

**Comment by GjjvdBurg** [comment]
Great, I'm digging around in the source now to see if I can figure it out. I'm on the 4.15.3-2-ARCH kernel and using go version `go1.10 linux/amd64`

**Comment by juruen** [comment]
The download logic is, in principle, simple:

1. Fetch the BlobURL
2. Create a temp file
3. Download blob to temp file
4. Move tmp file to actual location

```go
func (ctx *ApiCtx) FetchDocument(docId, dstPath string) error {
	documents := make([]model.Document, 0)

	url := fmt.Sprintf("%s?withBlob=true&doc=%s", listDocs, docId)

	if err := ctx.Http.Get(transport.UserBearer, url, nil, &documents); err != nil {
		log.Error.Println("failed to fetch document BlobURLGet %s", err)
		return err
	}

	if len(documents) == 0 || documents[0].BlobURLGet == "" {
		log.Error.Println("BlobURLGet for document is empty")
		return errors.New("no BlobURLGet")
	}

	blobUrl := documents[0].BlobURLGet

	src, err := ctx.Http.GetStream(transport.UserBearer, blobUrl)

	if src != nil {
		defer src.Close()
	}

	if err != nil {
		log.Error.Println("Error fetching blob")
		return err
	}

	dst, err := ioutil.TempFile("", "rmapifile")

	if err != nil {
		log.Error.Println("failed to create temp fail to download blob")
		return err
	}

	tmpPath := dst.Name()
	defer dst.Close()
	defer os.Remove(tmpPath)

	_, err = io.Copy(dst, src)

	if err != nil {
		log.Error.Println("failed to download blob")
		return err
	}

	err = os.Rename(tmpPath, dstPath)

	return nil
}
```

**Comment by GjjvdBurg** [comment]
True, I'm manually checking if the blobUrl points to anything, but that doesn't seem to be the problem, it just gives me the zip file.

**Comment by juruen** [comment]
I just tried on ubuntu 16.04 and Go 1.6.2 and it's working fine. 🤔 

Something that we could try is to check whether we are writing anything at all to the temp file.

**Comment by GjjvdBurg** [comment]
How could I check that?

**Comment by GjjvdBurg** [comment]
It does write to the temp file, if I remove the `defer os.Remove(tmpPath)` line, I'm left with the files in the /tmp directory

**Comment by juruen** [comment]
> How could I check that? They disappear rather quickly.

I would remove the  `defer os.Remove(tmpPath)` line and rebuild it with `go build`.

By the way, I just tried on ubuntu 16.04 and a newer version of Go: 1.10, and it seems to work fine. I'm still puzzled.

**Comment by juruen** [comment]
> It does write to the temp file, if I remove the defer os.Remove(tmpPath) line, I'm left with the files in the /tmp directory

Oh, I see that I'm not checking the `rename` errors :)

**Comment by GjjvdBurg** [comment]
Yeah, there seems to be an error in the `rename`, I get an "invalid cross device link"

**Comment by GjjvdBurg** [comment]
The "invalid cross device link" has to do with the fact that my `/tmp` is on a different partition than my `/home`, which is why `Rename` doesn't work.

**Comment by juruen** [comment]
> Yeah, there seems to be an error in the rename, I get an "invalid cross device link"

Sweet, that makes a lot of sense! You can only rename if they are in the same partition!

Fix incoming!

**Comment by GjjvdBurg** [comment]
Sweet!

**Comment by juruen** [comment]
@GjjvdBurg , fix is in master now. If you could please  give it a go to see if it works for you.

**Comment by GjjvdBurg** [comment]
@juruen It works now! Thanks a lot for your quick help!

**Comment by juruen** [comment]
@GjjvdBurg thank _you_ for finding the issue and report it!
