### ISSUE TITLE
get pdf with annotations

### ISSUE THREAD

**Issue by aryx** [juruen/rmapi#30]
When I 'get' a pdf I've annotated I get instead a zip file with 4 files in it (a .content, .lines, .pdf, and .pagedata). How do I get instead a pdf I can read with the line annotations in.

**Comment by dio4ev** [comment]
Try this tool:
https://github.com/jmptable/rm-dl-annotated

**Comment by juruen** [comment]
@peerdavid would you like to prepare a PR to integrate your changes upstream?

**Comment by peerdavid** [comment]
@juruen I opened the PR #34. Please check if you really want those additional dependencies (listed in README.md ). I.e. I create a SVG file for the annotations using python3 and afterwards a bash script is called that merges it with (1) the background or (2) with the pdf file using other tools that must be installed locally. For that reason I also decided to create a fork.

**Comment by lobre** [comment]
Can we consider this issue as resolved?

**Comment by lobre** [comment]
Resolved with https://github.com/juruen/rmapi/pull/38.

**Comment by lobre** [comment]
As it is only a first version, we can leave this issue open I think because so far the annotations are downloaded separately from the PDF.

**Comment by torwag** [comment]
Hi I came across this using rmapi today.
First, I really like rmapi, it is getting a work-horse for me, being on Linux and having no official app. 
I believe that most people expect that the downloaded version of a PDF contains the annotation and are a bit puzzled to see a zip file with plenty of unknown files for them.
Secondly, I exported the documents (forms) which I had signed on my rM, via rmapi and everything looked ok using zathura or evince on my host machine. I send the PDFs to a co-worker, and she said, the signature is missing. A bit surprised  I double-checked, on my linux machine, I had PDF with signature, she used Adobe Acrobat on a Windows machine and could not see the signature. I went to convert the PDFs into PNG and back into PDF, as this usually makes sure that all and everything is purely a static image and nothing can get lost. However, using imagemagick convert which utilities ghostscript to render a pdf into a png, the signature was missing. 
I ended up open the PDF in libreoffice (draw) and save it again as PDF, which seems to work.

Just as a feedback that the embedding of annotation seems not to be 100% compatible with all pdf readers.

**Comment by ddvk** [comment]
@torwag please provide a sample pdf

**Comment by torwag** [comment]
further description was done in #114 solved #115 merged upstream and distributed with release 0.0.12

**Comment by ddvk** [comment]
we can close this one for now, the export is not optimal, but enough for most people i think
