### ISSUE TITLE
failed to create new device token

### ISSUE THREAD

**Issue by ofosos** [juruen/rmapi#32]
Hi,
I get the following error, when I try to connect to the remarkable service:

```
mark@thukydides ~$ rmapi 
Enter one-time code (go to https://my.remarkable.com): xxxxxxxx
ERROR: 2018/10/09 08:23:54 auth.go:82: failed to create a new device token
```

Can you help me out here?

Thanks, Mark

**Comment by adem** [comment]
There was a change in the API endpoint URL. Did you update your packages via `go get-u all`? It's working fine for me as of today.

**Comment by ofosos** [comment]
After updating it's still not working for me :(

**Comment by ofosos** [comment]
Funky, after a `go get github.com/juruen/rmapi` it now works.

**Comment by ofosos** [comment]
Just to show off:
https://ofosos.org/2018/10/22/printing-to-remarkable-cloud-from-cups/

I'm priting from CUPS with `rmapi`.

Thanks for you help :)

**Comment by juruen** [comment]
>Just to show off:
>https://ofosos.org/2018/10/22/printing-to-remarkable-cloud-from-cups/



@ofosos nice! If you don't mind, I'd like to add the link to my list of `example of use`.

**Comment by ofosos** [comment]
juruen: please do so :)
