### ISSUE TITLE
Windows installation issue (undefined: Attr)

### ISSUE THREAD

**Issue by fuzzyBatman** [juruen/rmapi#39]
Attempting to install with `go get -u github.com/juruen/rmapi` on Windows gives

\# github.com/juruen/rmapi/vendor/github.com/hanwen/go-fuse/fuse
go\src\github.com\juruen\rmapi\vendor\github.com\hanwen\go-fuse\fuse\types.go:401:2: undefined: Attr

**Comment by juruen** [comment]
I removed the support for fuse for now.

Could you please try again?

**Comment by fuzzyBatman** [comment]
Perfect! No installation issues.
Thanks.
