### ISSUE TITLE
wsl installation issue

### ISSUE THREAD

**Issue by Xinzhu-Fang** [juruen/rmapi#51]
```
xfang@DESKTOP-693OACN:~$ go get -u github.com/juruen/rmapi

# github.com/juruen/rmapi/vendor/github.com/jung-kurt/gofpdf
go/src/github.com/juruen/rmapi/vendor/github.com/jung-kurt/gofpdf/fpdf.go:3335: undefined: sort.SliceStable
go/src/github.com/juruen/rmapi/vendor/github.com/jung-kurt/gofpdf/fpdf.go:3385: undefined: sort.SliceStable
go/src/github.com/juruen/rmapi/vendor/github.com/jung-kurt/gofpdf/fpdf.go:3484: undefined: sort.SliceStable
go/src/github.com/juruen/rmapi/vendor/github.com/jung-kurt/gofpdf/fpdf.go:3564: undefined: sort.SliceStable
go/src/github.com/juruen/rmapi/vendor/github.com/jung-kurt/gofpdf/fpdf.go:3598: undefined: sort.SliceStable
```

**Comment by juruen** [comment]
Did you try to upgrade your Golang version?

**Comment by Xinzhu-Fang** [comment]
Thanks for answering. I had difficulties upgrading but I no longer need the function that requires rmapi. So I am closing the issue for now. 
list of resources I had looked at:
https://gist.github.com/besser/2280c49ed0c8ffc43502e6b63241ed00
https://golangcode.com/updating-go-on-ubuntu/
https://stackoverflow.com/questions/42186003/how-to-uninstall-golang
https://www.tecmint.com/18-tar-command-examples-in-linux/
