### ISSUE TITLE
API v2 - Future design

### ISSUE THREAD

**Issue by lobre** [juruen/rmapi#54]
Hello @juruen,

I was interested about trying to build a second version of the API. I feel like the two packages `shell` and `api` are quite dependant, as well as the `log` package. When used externally (e.g. @jessfraz has built https://github.com/jessfraz/morningpaper2remarkable), we need to init the log `log.InitLog()` and even if we just want to put a file on the device for instance, I feel like we need to import multiple `rmapi` packages.

For instance, as far as I understand, the `ApiCtx` has a notion of FileTree but for me the FileTree is mostly related to the shell. The API could only have the responsibility of authentication and interaction with the Remarkable Cloud with simple functions that would build a simple interface seen from the outside (more or less CRUD operations like CreateFile, GetFile, UpdateFile, DeleteFile).

The `shell` package would only become an "implementation" using the `api` the same way other external clients might do.

And speaking about authentication, the only way to authenticate with the current implementation is to have the `.rmapi` file with credentials inside. If I just want to upload a file into the Remarkable Cloud from my external Golang tool, I would have to create this file. I think that could be done more easily using some sort of other mecanisms.

All of this is just me trying to reflect about the different packages structure and role in this project :D). This is not super important as the current implementation works actually well. But I am thinking that maybe if we improve little things like this, the tool would become even more powerful in the Golang community.

Don't know what you think of all of this but it would be nice to have your mindset about it ;).
And maybe if that can make sense, that could be interesting to try to think about a future design or about how the tool can evolve! (not sure if many people have time to spend for all of this but I still find the challenge interesting).

Maybe I am also wrong on my assumptions and I don't fully understand the architecture and purposes of this project... Let me know!

Thanks,
Loric

**Comment by juruen** [comment]
> Maybe I am also wrong on my assumptions and I don't fully understand the architecture and purposes of this project... Let me know!

You are absolutely right!

Two things to note:

1. The current implementation was my first Go project, so I've probably made any newbie mistake that could be made from a language perspective :)
2. As you point out the `shell` package is the first `user` of the  current API, and in my opinion, the current API is not high-level enough. The shell is doing a lot of work that could be perfectly abstracted, I'm not sure whether that should happen in the `api` package or in `client` package. But doing things such as uploading a file should be super simple. This would obviously make the `morningpaper2remarkable` case easier to implement.

> And speaking about authentication, the only way to authenticate with the current implementation is to have the `.rmapi` file with credentials inside. If I just want to upload a file into the Remarkable Cloud from my external Golang tool, I would have to create this file. I think that could be done more easily using some sort of other mecanisms.

Agreed!

**Comment by lobre** [comment]
> The current implementation was my first Go project.

Cool! And very nice for a first project. I am as well not super experimented in Golang as I started using it maybe 6 months ago. But I begin to see the power of well defined and well scoped packages and it is always fun to try to design/name them!

> I'm not sure whether that should happen in the `api` package or in `client` package.

I did not realize but effectively, maybe `client` is more appropriated as it brings bindings for an existing API. But I don't see this as a real problem as `api` is still expressive.

> In my opinion, the current API is not high-level enough.

Do you have an example of something present in the `shell` package that would normally reside in the `api` package according to you? Just to grasp the idea...

Maybe we could use this issue to talk and discuss about what should exactly be the `api` package. And we can see in a second time for a potential implementation. What could be nice is to reflect on the definition of exposed methods and functions of a "perfect" `api` package.

I'll try to elaborate a draft and post it here.

**Comment by lobre** [comment]
Hello,

Here is what I came up with so far. It is not much. These are just ideas. Would like to hear if they make sense ;)

Disclaimer: a did not take a lot of time digging in the actual `api` package, so there might be interesting things to keep and integrate!

---

The article below recommends good practices that I find intersting for coding an API client in Golang.

[Writing a Go client for your RESTful API](https://medium.com/@marcus.olsson/writing-a-go-client-for-your-restful-api-c193a2f4998c)

We first need a `Client` struct that contains a reference to the `http.Client` used to make requests to the Remarkable API.

    type Client struct {
        BaseURL   *url.URL
        UserAgent string
     
        httpClient *http.Client
    }

Marcus Olsson from the article recommends to factorize some internal functions that will be called for the HTTP transport.

    func (c *Client) newRequest(method, path string, body interface{})
    func (c *Client) do(req *http.Request, v interface{})

# Authentication

We should let users configure their own `http.Client`. This also allows to handle authentication outside the `Client`. See the example from google/go-github.

    ts := oauth2.StaticTokenSource(
        &oauth2.Token{AccessToken: "... your access token ..."},
    )
    tc := oauth2.NewClient(oauth2.NoContext, ts)
    client := github.NewClient(tc)

So we can image having a constructor with this definition.

    func NewClient(httpClient *http.Client) *Client

# Service discovery

Apparently, according to the splitbrain documentation about the Remarkable API, we need to call a Service Discovery endpoint to fetch the hosts that should be queried. See the following page for more information.

[splitbrain/ReMarkableAPI](https://github.com/splitbrain/ReMarkableAPI/wiki/Service-Discovery)

That means we will need a `checkServiceDiscovery` method for this purpose. This should not be exposed.

# Storage

[splitbrain/ReMarkableAPI](https://github.com/splitbrain/ReMarkableAPI/wiki/Storage)

We then need structs for data models. From the documentation from splitbrain, it seems that the vocabulary of Remarkable uses the following.

- A **Document** is Notebook.
- A **Collection** is a Folder.
- An **Item** is one of a Document or a Notebook.

We can use the same name conventions.

## List of actual HTTP methods

- document-storage/json/2/docs (used for listing one or several items and downloading)
- document-storage/json/2/upload/request (used for uploading a document)
- document-storage/json/2/upload/update-status (updating meta-data and creating folder)
- document-storage/json/2/delete (deleting items)

From all the actual methods, we will chose to expose certain more logical methods in the Golang client.

## List of final Golang methods

We need to find the correct granularity and define methods that are not too close / not too far from the actual API. It should be handy to use at a user level. It should help to have a conventionally goish way of interacting with Remarkable notes.

Next steps? Precisely think about this last point and define a set of Golang methods that would make a consistent API.

**Comment by juruen** [comment]
Great write up!

Sorry for the radio silence by the way, but am a bit busy with our new 👶 :)

I like what I'm reading but I would like to make sure we are on the same page first.

I'd be super happy to refactor the API following the above recommendations, and pretty much ending up with an implementation of the rM HTTP endpoints.

But I still think we should offer a higher level abstraction on top of that, call it `client` if you want that uses the `API` but takes care of the common tasks library users would like to use it for.

**Comment by lobre** [comment]
> Sorry for the radio silence by the way, but am a bit busy with our new baby :)

Congrats! And no worries, open source projects don't require as much attention as a baby! :-)

Defining the level abstraction was exactly what I was referring to when saying:

> We need to find the correct granularity and define methods that are not too close / not too far from the actual API.

And I can agree that a high level would be interesting from a user perspective. General actions like:
 - upload a note
 - download a note
 - create directory
 - delete note or directory
 - download all notes
 - delete all notes

In fact, these are common actions around notes that avoid thinking too much about the technical aspects and the underlying API calls.

If it is something complicated to abstract, maybe it can also be useful to create two levels of abstraction. High (like above) and a lower one for more technical operations. Like git with Plumbing and Porcelain. Or may be it is not worth it to think about a such complicated architecture for a simple API like this.

**Comment by jessfraz** [comment]
Love all of this :) would love to integrate it into mine :)

**Comment by lobre** [comment]
Hello!

I have submitted a PR with an implementation of what has been discussed here.
I added a few information in the PR message so you can quickly understand it without digging too much into the code.

Have a nice day,
Loric

**Comment by lobre** [comment]
This has been merged with #64.
