### ISSUE TITLE
rmapi broken on OS X for cups printing

### ISSUE THREAD

**Issue by ThorbenJ** [juruen/rmapi#59]
Hi,

There is a cups backend script that uses rmapi to "print" documents to your remarkable (https://ofosos.org/2018/10/22/printing-to-remarkable-cloud-from-cups/).

However this script runs in a restricted environment protected by OS X's SIP. As such the rmapi executable (located in /usr/local/bin, or it may not be executed) may not open /var/spool/cups/.rmdir; the operation is denied by SIP.

```
WARNING: 2019/06/27 11:47:05 config.go:40: failed to open /var/spool/cups/.rmapi with open /var/spool/cups/.rmapi: operation not permitted/n
Enter one-time code (go to https://my.remarkable.com): ERROR: 2019/06/27 11:47:05 auth.go:62: Code has the wrong length, it should be 8
Enter one-time code (go to https://my.remarkable.com): ERROR: 2019/06/27 11:47:05 auth.go:62: Code has the wrong length, it should be 8
Enter one-time code (go to https://my.remarkable.com): ERROR: 2019/06/27 11:47:05 auth.go:62: Code has the wrong length, it should be 8
Enter one-time code (go to https://my.remarkable.com): ERROR: 2019/06/27 11:47:05 auth.go:62: Code has the wrong length, it should be 8

(infinite loop here, please also fix)
````

HOME for user "_lp" is /var/spool/cups. Note SIP is not based on POSIX permissions (SELinux but for OS X), and I do not want to disable it. I would rather have rmapi read from a permitted location.

Please allow one to override this files location with an environment variable (RMAPI_CONF or RMAPI_TOKEN etc) or a command argument. So one could open a file path that is allowed by SIP.

Thanks,
Thorben

**Comment by lobre** [comment]
Hello,

That would be a nice option to let configure the location of this file effectively.
I was wondering if it would fix to run rmapi with the following command:

`HOME=/tmp/mynew/home rmapi put myfile.pdf`

But `rmapi` relies on the `os/user` package that itself does not rely on environment variables to gather the home directory. So wrong idea.

```
❯ go doc os/user
package user // import "os/user"

Package user allows user account lookups by name or id.

For most Unix systems, this package has two internal implementations of
resolving user and group ids to names. One is written in pure Go and parses
/etc/passwd and /etc/group. The other is cgo-based and relies on the
standard C library (libc) routines such as getpwuid_r and getgrnam_r.

When cgo is available, cgo-based (libc-backed) code is used by default. This
can be overriden by using osusergo build tag, which enforces the pure Go
implementation.
```

It apparently takes the information from `/etc/passwd` (in Unix based systems).

I have submitted a really quick PR that could potentially do the trick. Warning: I did not test at all, it is just a quick draft.

https://github.com/juruen/rmapi/pull/60

Loric

**Comment by ThorbenJ** [comment]
I can't test it, but I have a feeling that ".dotfiles" are being blocked by SIP; so "$HOME/.rmapi" might not work either.

**Comment by ThorbenJ** [comment]
I just made the following change to config.go:
```
func ConfigPath() string {
        return "/etc/cups/rmapi.conf"

        user, err := user.Current()
        if err != nil {
                log.Error.Panicln("failed to get current user:", err)
        }

        home := user.HomeDir

        return fmt.Sprintf("%s/%s", home, defaultConfigFile)
}
```

And the cups printing is now working. BTW /var/spool/cups/rmdir was also denied.

A better fix would be to have a list of locations and use the first one that `stat` says is readable/exists. Say for example:

- $RMAPI_CONFIG
- $RMAPI_CONFIG/[default_file_name]
- $XDG_CONFIG_DIR/[default_file_name]
- $HOME/[default_file_name]

**Comment by lobre** [comment]
I am not sure to understand.
With the PR I submitted, wouldn't it be the same result as your last comment if you set the environment variable `RMAPI_HOME=/etc/cups`?

**Comment by ThorbenJ** [comment]
It was a quick and dirty test; in parallel to your posting.

Also I wanted to avoid the filename starting with a dot '.' (defaultConfigFile = ".rmapi").

My suggestion about testing multiple paths was because I saw other issues open about support XDG standard paths.

**Comment by lobre** [comment]
XDG brings good recommendations I think as well. But it's only a Linux concept. Does not apply on Windows for instance. Finding a path appropriate to the OS is a topic in Golang. Some packages try to answer this purpose. 

For instance: https://github.com/shibukawa/configdir

What is important I think is to define the requirements we want for rmapi and apply this in a self contained proper package (currently `config`).

Do we want to make this package more complicated than it is for such a simple task? A full path (including the file name) that can be set using an environment variable might be enough.

Well that is a good question. Maybe @juruen has a opinion on this?

**Comment by juruen** [comment]
> Do we want to make this package more complicated than it is for such a simple task? A full path (including the file name) that can be set using an environment variable might be enough.

Yeah, I'm more inclined towards just going with a full path variable as the simplest way forward.
