### ISSUE TITLE
Printing to rM requires device reset to download

### ISSUE THREAD

**Issue by jheats** [juruen/rmapi#61]
Hi - great tool, thanks very much.

I recently upgraded to the latest rM version 1.7.2.3 before trying your api so this may be related to the upgrade or it may not, I'm afraid I don't know.

Anyway, I followed the print to reMarkable tutorial and it works really well, except that the file doesn't actually download to the tablet unless I turn it off and on again (and equally, isn't available in the rM cloud client without restarting it).  The file does appear very promptly, but generally says 'Page 1 of 0' and then we you select it, there's nothing there.

Any advice much appreciated.

Best wishes

James

**Comment by jheats** [comment]
Update: I am getting the same issue when just using the rmapi put command in the terminal - file appears promptly but content is not actually there without a restart.

**Comment by dbosk** [comment]
Sounds very much like #57. Sent from my less-usable device-------- Original Message --------Subject: Re: [juruen/rmapi] Printing to rM requires device reset to download (#61)From: jheats To: juruen/rmapi CC: Subscribed Update: I am getting the same issue when just using the rmapi put command in the terminal - file appears promptly but content is not actually there without a restart.

**Comment by jheats** [comment]
Thanks.  It was indeed #57 - I am fixed as of this morning having rebuilt from source.  I think the zip file referenced on https://github.com/juruen/rmapi/blob/master/docs/tutorial-print-macosx.md may need updating since that fix.
