### ISSUE TITLE
incorrect error message "Code has the wrong lenth, it should be 8"

### ISSUE THREAD

**Issue by cmougin** [juruen/rmapi#7]
after having locally rebuilt the exec file (RMAPI.EXE) from the github sources:

C:\Utilisateurs\FR20340\go\bin>rmapi.exe
Enter one-time code (go to https://my.remarkable.com): uitaahkl
ERROR: 2018/02/26 19:27:18 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com): uitaahkl
ERROR: 2018/02/26 19:27:24 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com): uitaahkl
ERROR: 2018/02/26 19:27:25 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com): uitaahkl
ERROR: 2018/02/26 19:27:26 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com): uitaahkl
ERROR: 2018/02/26 19:27:26 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com): uitaahkl
ERROR: 2018/02/26 19:27:27 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com): 12345678
ERROR: 2018/02/26 19:27:31 auth.go:59: Code has the wrong lenth, it should be 8
Enter one-time code (go to https://my.remarkable.com):

**Comment by juruen** [comment]
Hi @cmougin,

It seems an issue with the new line in Windows. Give me a few minutes to push a commit to fix it.

**Comment by juruen** [comment]
@cmougin 

I just pushed a fix to master. Could you please try again and let te me know whether it solves the issue.

Thank you!

**Comment by juruen** [comment]
@cmougin I'm closing this. I finally found some time to build mater on Windows 10 and it works fine after a couple of changes I introduced a few days ago.
