### ISSUE TITLE
Add Dockerfile?

### ISSUE THREAD

**Issue by ClaytonJY** [juruen/rmapi#70]
Would there be any interest in having a Dockerfile for this project?

Go & `rmapi` are quite easy to install directly, but I recently made a dockerfile for a python project which leverages `rmapi`, and it gets a little messier:  https://github.com/GjjvdBurg/arxiv2remarkable/pull/5

It may benefit the `rmapi`-based ecosystem to have an "official" Dockerfile they can start from.

I'd be happy to submit a PR, and rather than the python-base approach I used above I'd aim for something more like https://github.com/jessfraz/morningpaper2remarkable: multi-stage, alpine-based, etc. Also happy to help setup pushing to Dockerhub via CI (azure?) and whatever else seems related and useful.

**Comment by juruen** [comment]
> Would there be any interest in having a Dockerfile for this project?

Sure! Some people out there may find it easier to test or run it on  docker.
