### ISSUE TITLE
Building version 0.0.6

### ISSUE THREAD

**Issue by lobre** [juruen/rmapi#71]
Hi @juruen,

We the new package `api.v2`, I was wondering if we could create a new version of the module with this package included (from `master`). Otherwise, we cannot use it in external modules because the automatic most recent version of the module `github.com/juruen/rmapi` is 0.0.5.

And at the same time, maybe you can explain the process to create a new release? Is it manual?

Thanks a lot,
Loric

**Comment by lobre** [comment]
At the same time, I take advantage of this issue to re-introduce the project I started working on: https://github.com/lobre/rmuploader.

It is a simple interface to upload a PDF or an EPUB from the web to the Remarkable tablet. I have adapted it to use the latest `api.v2` package in combination with the `archive` package. I think it can be a good example for other people wanting to use `rmapi`.

Maybe I can add a reference to this project in the `README.md` of `rmapi`?

What is currently missing in `rmuploader` (but planned to be done ASAP):
 - the build is failing because `api.v2` is not found in `rmapi` v0.0.5 (hence this PR)
 - finalize a Docker image to easily launch it
 - add some documentation
 - add a new feature: add a new input text on the web interface to allow to enter a URL of a blog/website page; then on submit, the package `go-wkhtmltopdf` would be used to create a PDF version of the webpage and the result would be sent to the Remarkable (I want this because I really miss a way to easily switch from my computer to my tablet when I want to read a blog post).

And finally, if all of this `rmuploader` is a success and works well, I hope to find time to adapt the `shell` package of `rmapi` to use it...

**Comment by juruen** [comment]
> And at the same time, maybe you can explain the process to create a new release? Is it manual?

It used to be manual. However, I had some time today, and I automated most part of it with GitHub Actions and a script. Take look at https://github.com/juruen/rmapi/blob/master/docs/create-release.md

I used that process to release `v0.0.6`.


> Maybe I can add a reference to this project in the `README.md` of `rmapi`?

Certainly. That's pretty neat project!
