### ISSUE TITLE
Deployment on server (heroku)

### ISSUE THREAD

**Issue by briankaemingk** [juruen/rmapi#73]
Hi all - This is an amazing project, thank you! 

Has anyone tried to deploy this on a non-local server like Heroku and gotten authentication to work? I have a local version working--I can execute ./rmapi, type in the one time code, and it works as expected. However, when I deploy to the server, it hangs. I assume it's stuck on the one time code, but there's no logging message associated with it, and I'm not sure the best way to input and/or store the one time code. Any ideas?

I'm not sure if this is really an issue, but I don't really know where to put this, so I thought I would raise it to the community here to see if anyone with more experience than I with golang or rMAPI has encountered this. Appreciate it!

**Comment by briankaemingk** [comment]
I was having trouble with authentication when deploying to the server, but I figured it out when I discovered the .rmapi file in the docs. Deployed and working on the server!

In any case, I'm interested in whether others have tried to deploy and best practices for that. Specifically on using environment variables instead of committing the .rmapi file.

Thanks again!

**Comment by lobre** [comment]
Hi, sorry for the late reply.

Maybe you can explain a little bit more your usecase?

For me, `rmapi` is a CLI application that has been created for humans.
I guess you are trying to use it through some automated scripts or other custom application?

If this happens to become a use-case, the idea would be to try to make a few changes to use it in a non-interactive way.

The one-code authentication is effectively prompted through the standard input which is not really handy for your purpose.

Loric
