### ISSUE TITLE
Make archive.Zip a proper io.Reader/ io.Writer

### ISSUE THREAD

**Issue by dyedgreen** [juruen/rmapi#74]
I think it would improve the API ergonomics if `archive.Zip` would implement an `io.ReadWriter`.

That way, you can still use intermediate buffers for downloading / caching, but can then chain these using the standard io methods. Also, the following would be possible:

```golang
zip := archive.NewZip()
client.Download(doc.ID, zip)
```

From what I can tell, the `zip.Read()`/`zip.Write()` functions have an internal buffer already, so making it an `io.ReadWriter` should not have any negative effects in that regard.

**Comment by lobre** [comment]
I am not sure if that would be a good idea. I never really had to implement `io.Reader`/`io.Writer` before but as far as I understand, it makes sense to do this when the type supports "streaming".

I thought `archive/zip` (backing all the `archive/zip` implementation) could zip/unzip on the fly in a streaming manner but it apparently can't (I started this StackOverFlow thread regarding this: https://stackoverflow.com/questions/57969180/should-i-implement-io-reader-io-writer-if-my-type-does-not-make-sense-as-a-strea). It has to seek anyway into the global zip structure to write/read at the end of the file. So if wanting to read a zip file with `archive/zip`, we should have all the bytes of the file transfered.

If we wished to implement `io.Reader`/`io.Writer`, we would effectively have to buffer the final compiled zip file inside the `archive.Zip` to stream it afterwards which I think is not super ideal.

> From what I can tell, the zip.Read()/zip.Write() functions have an internal buffer already

I am not sure to understand where the internal buffer resides in the `Write` method. Can you help explaining where plz?

For the `Read` method, I guess you are refering to the `zipReaderFromIOReader(r)` function?

I would be more in favour of trying to remove these explicit buffers and try to lighten and use the `archive/zip` package as transparently as possible.

The standard library still provides `io.Pipe` that can help redirecting an `io.Reader` to a `io.Writer`. See the implementation I started on a unfinished personal project here: https://github.com/lobre/rmuploader/blob/master/rm.go#L33

All of this is however kinda new to me, I did not have to experiment a lot with it in Go. I am open to talk about it if there is anythink I would have misunderstood.

**Comment by dyedgreen** [comment]
> I am not sure if that would be a good idea. I never really had to implement `io.Reader`/`io.Writer` before but as far as I understand, it makes sense to do this when the type supports "streaming".

Yeah, I think you're right here. Since the whole zip has to be read before it can be decoded in the `archive.Zip`, it makes more sense to consume a reader (as you can read until `io.EOF`). Then, using an `io.Pipe` is the best option for the example I provided, as you said 😄

> I am not sure to understand where the internal buffer resides in the Write method. Can you help explaining where plz?

I was referring specifically to the buffer used for `.Read()`. (Although, I suppose the data structure itself also might be thought of as a buffer for the `.Write()` function.)

**Comment by dyedgreen** [comment]
(Thank you for the quick reply, by the way 😃)

**Comment by lobre** [comment]
I reopen this issue to add a PR to take an `io.ReaderAt` instead of an `io.Reader` in the `zip.Read` method. This removes the need of buffering the entire file during this process.

**Comment by lobre** [comment]
Merged.
