### ISSUE TITLE
geta is generating blank pdf

### ISSUE THREAD

**Issue by OpoOpo** [juruen/rmapi#76]
When I use geta on some hand written note it generates blank pdf with correct number of pages.

**Comment by lobre** [comment]
Are you using the latest version of the Remarkable software? If so, your issue might be related to #67 which is not yes implemented.

**Comment by OpoOpo** [comment]
Yes, I am using 1.8 version.
Sorry i did not noticed this issue (#67).

**Comment by lobre** [comment]
Okay so I guess this is related. The project is not super active but the upgrade to 1.8 is definitely a high priority in the roadmap.

**Comment by lobre** [comment]
I close this one as we can follow the evolution in #67.
