### ISSUE TITLE
Code has the wrong length error message

### ISSUE THREAD

**Issue by isovector** [juruen/rmapi#77]
Hi there,

I'm attempting to follow the instructions [here](https://github.com/ofosos/scratch/tree/master/remarkable-cups), but my CUPS endpoint fails with the error message `"Idle - "2019/10/07 17:19:46 auth.go:62: Code has the wrong length, it should be 8""`

https://github.com/ofosos/scratch/issues/6

```
$ rmapi version
ReMarkable Cloud API Shell
rmapi version: 0.0.6
```

**Comment by juruen** [comment]
You need to run `rmapi` at least once from the terminal to introduce a new activation code. See [this](https://github.com/juruen/rmapi/blob/master/docs/tutorial-print-macosx.md#run-rmapi-for-first-time) for more info.

Once you do that, you'll have a `.rmapi` file in your `$HOME` directory.

Make sure that file is read by `rmapi` from your cups file.

**Comment by isovector** [comment]
Thanks. I didn't realize `cups` ran as a different user than I do. My fix was here:

https://github.com/ofosos/scratch/issues/6#issuecomment-548511788

That being said, there might be a better error message to produce in this case :)
