### ISSUE TITLE
How to pass two commands to rmapi in shell script?

### ISSUE THREAD

**Issue by Mehechiger** [juruen/rmapi#8]
I'd like to do something with mac's printer plugin like, rmapi cd folder1 put file1 exit, but I don't know the right grammar. thank you

**Comment by Mehechiger** [comment]
Never mind, found a way with echo.

**Comment by fabianmu** [comment]
@Mehechiger how did you do it? I also need to `put` a file into a folder

**Comment by juruen** [comment]
@fabianmu 

You can do this  on Mac or Linux:

```bash
echo -e "cd books\nput new_book.pdf" | rmapi
```

Just split the commands with `\n`

**Comment by juruen** [comment]
@fabianmu 

I just pushed to master a version where put can take a destination directory:

https://github.com/juruen/rmapi/commit/21f7a7546882543e04a4b2ead9263f516ba7a409

**Comment by fabianmu** [comment]
ah, yeah piping does the trick, thanks for pushing the update to specify a destination dir @juruen !

**Comment by juruen** [comment]
@fabianmu 

> ah, yeah piping does the trick, thanks for pushing the update to specify a destination dir @juruen !

I'm glad I could help!
