### ISSUE TITLE
Put fails if entry exists in top-level directory

### ISSUE THREAD

**Issue by GjjvdBurg** [juruen/rmapi#86]
This issue was raised in gjjvdburg/paper2remarkable#22, but I believe the problem lies with rmapi.

If a file is uploaded with ``put`` and a destination directory is provided, the upload fails if a file with the same name already exists in the top-level directory.

Steps to reproduce:
1. ``rmapi put test.pdf``
2. ``rmapi mkdir Test``
3. ``rmapi put test.pdf Test/`` fails with "entry already exists"

This bug seems to be due to the fact that the put command checks if the entry exists before figuring out the destination directory, instead of the other way around.

Thanks for the help!

**Comment by juruen** [comment]
Yeah, you can't have a directory and a file with the same name.

We can definitely support this so I'll take a look. Thanks!

**Comment by dbosk** [comment]
> Yeah, you can't have a directory and a file with the same name.

The truth of that statement is debatable :-)
```
rmapi mkdir testdir
rmapi put test.pdf testdir
rmapi put test.pdf testdir
rmapi ls testdir
```
will output only one test.pdf. But the reMarkable will handle the two copies, so in the device interface you'll find both of them --- with the same name!

**Comment by GjjvdBurg** [comment]
Closing this due to #95 being merged.
