### ISSUE TITLE
Getting one-time codes

### ISSUE THREAD

**Issue by finnove** [juruen/rmapi#87]
Hi, I logged in to my remarkable, but there is no way to get a one time code. How did you manage to get the code? It reads: Only one tablet can be connected to my account.

**Comment by merqurio** [comment]
Log in to their site and look for a link with the text:

> Reconnect your reMarkable

It will give you a code that AFAIK work with `rmapi`

**Comment by finnove** [comment]
Awesome! That did the trick, thanks!
