### ISSUE TITLE
proxy issue ?

### ISSUE THREAD

**Issue by cmougin** [juruen/rmapi#9]
Hello,
I'm back to my keyboard after some (good) time spent away from it.
thank you for having fixed the issue on the trailing \r\n, I can go one step further.
Now here's the new issue. I'm not familiar to GO language, but more to Python, Java, C, … and I read that GO was supporting proxy if the environment variable was set. Then I tried this: "set http_proxy=proxy.priv.atos.fr:3128 && rmapi.exe" [on Windows 7], and I get this output:
Enter one-time code (go to https://my.remarkable.com): oavbeysl
ERROR: 2018/03/13 16:18:03 transport.go:174: http request failed with%!(EXTRA *url.Error=Post https://my.remarkable.com/token/device/new: proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.)
ERROR: 2018/03/13 16:18:03 auth.go:82: failed to create a new device token
Checking if the var is ok seems correct, see below:
> C:\Utilisateurs\FR20340\go\bin>set http_proxy
> http_proxy=proxy.priv.atos.fr:3128
> C:\Utilisateurs\FR20340\go\bin>
any clue ?
cheers
Christophe

**Comment by ddvk** [comment]
it works with proxy, but you have to set **https_proxy** e.g

https_proxy=localhost:8080 rmapi ls
