### ISSUE TITLE
Uknown rune on get

### ISSUE THREAD

**Issue by luerhard** [juruen/rmapi#96]
Hey there, thank you very much for this nice and handy tool.
I just have a problem with ukwnon runes. As I am German and am used to name my academic papers according to their authors (actually zotero does that), I have no problem uploading them via the normal Windows tool, but I can't access files with special characters via rmapi on Arch.

I am using the 0.0.9 version from AUR.

```
[/to read]>geta Oeltjen_Windzio_2019_Räumliche\ Segregation\ durch\ ungleiche\ Bildungskontexte
Error: Uknown rune: 228
[/to read]>get Möser\ et\ al_2019_Valuation\ of\ labour\ market\ entrance\ positions\ among\ (future)\ apprentices\ -
Error: Uknown rune: 246
[/to read]>get Fischer-Preßler\ et\ al_2019_Collective\ sense-making\ in\ times\ of\ crisis
Error: Uknown rune: 223
```

**Comment by ddvk** [comment]
there is an issue with the shell package (https://github.com/abiosoft/ishell/issues/22)
the workaround is to surround the name with quotes "

**Comment by luerhard** [comment]
oh very well, that'll do for now :) thanks ! 
the issue is over 3 year old though.
