### ISSUE TITLE
geta of annotated PDF shrinks and mirrors pen notes, but correctly renders marker (for some PDFs)

### ISSUE THREAD

**Issue by fmagin** [juruen/rmapi#97]
Using version `0.0.10` from the Arch User Repository with a device version of `2.0.2.0`
I haven't exhaustively tested this, because it actually works for all the PDFs I tested that I actually care about, but at least one other PDF was broken.

This issue isn't urgent for me, the PDFs I actually want to read and annotate work fine, I just found this accidentally while testing the PDF Export.

The PDF is of the article https://blog.cloudflare.com/speeding-up-linux-disk-encryption/ generated by opening the Reader Mode in Chromium and then using the Print To Remarkable Plugin to send this to the device.

The drawings on the right are all the tools in the order they appear in the menu

On the device:

![image](https://user-images.githubusercontent.com/8415354/79849867-5a981880-83c3-11ea-912f-06f17431d9fe.png)
 
Returned PDF (with `geta`), rendered in Chromium:

![image](https://user-images.githubusercontent.com/8415354/79850155-ca0e0800-83c3-11ea-9bb5-2256e6d0d25a.png)

The marker is rendered correctly, but all the other drawings that would cover the entire page are flipped horizontally and shrunken in the top right corner.

ZIP file returned by `get`: 
[Speeding up Linux disk encryption.zip](https://github.com/juruen/rmapi/files/4509224/Speeding.up.Linux.disk.encryption.zip)

I can upload the PDFs if this isn't reproducible or if the issue isn't obvious for some reason anyway. I guess the hint that the marker is rendered correctly should make it fairly easy to track down.

**Comment by ddvk** [comment]
on the device, any view adjustment?

**Comment by fmagin** [comment]
Nope.

**Comment by ddvk** [comment]
can you upload somewhere the zip you get when you do a rmapi get

**Comment by fmagin** [comment]
Added it to the initial description.
